/*
CREATED: 22/10/2017
MODIFIED: 17/12/2017
MODEL: POSTGRESQL 9.4
DATABASE: POSTGRESQL 9.4
*/


-- DROP INDEXES SECTION -------------------------------------------------

DROP INDEX IF EXISTS IDX_UTENTI_USERNAME
;
DROP INDEX IF EXISTS IDX_UTENTI_PK
;
DROP INDEX IF EXISTS IDX_UTENTI_LINGUE_PK
;
DROP INDEX IF EXISTS IDX_UTENTI_LINGUE_FK
;
DROP INDEX IF EXISTS IDX_PASSWORD_FK
;
DROP INDEX IF EXISTS IDX_PROFILI_1
;
DROP INDEX IF EXISTS IDX_PROFILI_PK
;
DROP INDEX IF EXISTS IDX_MENU_PROFILI_FK
;
DROP INDEX IF EXISTS IDX_MENU_PROFILI_PK
;
DROP INDEX IF EXISTS IDX_MENU_PK
;
DROP INDEX IF EXISTS IDX_MENU_TREE
;
DROP INDEX IF EXISTS IDX_UTENTI_PROFILI_PK
;
DROP INDEX IF EXISTS IDX_UTENTI_PROFILI_FK
;


-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE IF EXISTS UTENTI_LINGUE CASCADE
;
DROP TABLE IF EXISTS UTENTI_PROFILI CASCADE
;
DROP TABLE IF EXISTS MENU_LINGUE CASCADE
;
DROP TABLE IF EXISTS MENU_PROFILI CASCADE
;
DROP TABLE IF EXISTS MENU CASCADE
;
DROP TABLE IF EXISTS LINGUE_ISO CASCADE
;
DROP TABLE IF EXISTS PROFILI CASCADE
;
DROP TABLE IF EXISTS PARAMETRI CASCADE
;
DROP TABLE IF EXISTS PASSWORD CASCADE
;
DROP TABLE IF EXISTS UTENTI CASCADE
;

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE PUBLIC.UTENTI

CREATE TABLE UTENTI(
 ID_UTENTE SERIAL NOT NULL,
 USERNAME CHARACTER VARYING(50) NOT NULL,
 COGNOME CHARACTER VARYING(50) NOT NULL,
 NOME CHARACTER VARYING(50) NOT NULL,
 EMAIL CHARACTER VARYING(100) NOT NULL,
 TS_LOGIN TIMESTAMP,
 ID_UTENTE_INS INTEGER,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 FL_DISATTIVO BOOLEAN DEFAULT FALSE NOT NULL
)
;

-- CREATE INDEXES FOR TABLE PUBLIC.UTENTI

CREATE INDEX IDX_UTENTI_USERNAME ON UTENTI (USERNAME)
;

CREATE INDEX IDX_UTENTI_PK ON UTENTI (ID_UTENTE)
;

-- ADD KEYS FOR TABLE PUBLIC.UTENTI

ALTER TABLE UTENTI ADD CONSTRAINT PK_UTENTI PRIMARY KEY (ID_UTENTE)
;

ALTER TABLE UTENTI ADD CONSTRAINT K1_UTENTI UNIQUE (ID_UTENTE)
;

ALTER TABLE UTENTI ADD CONSTRAINT K2_UTENTI UNIQUE (USERNAME)
;

-- TABLE PASSWORD

CREATE TABLE PASSWORD(
 ID_PASSWORD SERIAL NOT NULL,
 ID_UTENTE INTEGER NOT NULL,
 PASSWORD CHARACTER VARYING(50) NOT NULL,
 DT_SCADENZA CHARACTER(10),
 FL_VALIDA BOOLEAN NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
;

-- CREATE INDEXES FOR TABLE PASSWORD

CREATE INDEX IDX_PASSWORD_FK ON PASSWORD (ID_PASSWORD,ID_UTENTE)
;

-- ADD KEYS FOR TABLE PASSWORD

ALTER TABLE PASSWORD ADD CONSTRAINT PK_PASSWORD PRIMARY KEY (ID_PASSWORD,ID_UTENTE)
;

ALTER TABLE PASSWORD ADD CONSTRAINT K1_PASSWORD UNIQUE (ID_PASSWORD)
;

-- TABLE PARAMETRI

CREATE TABLE PARAMETRI(
 ID_PARAMETRO SERIAL NOT NULL,
 DOMINIO CHARACTER(3) NOT NULL,
 CODICE CHARACTER(3) NOT NULL,
 DESCRIZIONE CHARACTER VARYING(50) NOT NULL,
 ORDINE INTEGER DEFAULT 0 NOT NULL,
 FL_DISATTIVO BOOLEAN DEFAULT FALSE NOT NULL
)
;

-- ADD KEYS FOR TABLE PARAMETRI

ALTER TABLE PARAMETRI ADD CONSTRAINT PK_PARAMETRI PRIMARY KEY (ID_PARAMETRO)
;

-- TABLE PROFILI

CREATE TABLE PROFILI(
 ID_PROFILO SERIAL NOT NULL,
 CODICE CHARACTER(3) NOT NULL,
 DESCRIZIONE CHARACTER VARYING(50) NOT NULL
)
;

-- CREATE INDEXES FOR TABLE PROFILI

CREATE INDEX IDX_PROFILI_1 ON PROFILI (CODICE)
;

CREATE INDEX IDX_PROFILI_PK ON PROFILI (ID_PROFILO)
;

-- ADD KEYS FOR TABLE PROFILI

ALTER TABLE PROFILI ADD CONSTRAINT PK_PROFILI PRIMARY KEY (ID_PROFILO)
;

ALTER TABLE PROFILI ADD CONSTRAINT K_PROFILI_2 UNIQUE (CODICE)
;

ALTER TABLE PROFILI ADD CONSTRAINT K_PROFILI_1 UNIQUE (ID_PROFILO)
;

-- TABLE LINGUE_ISO

CREATE TABLE LINGUE_ISO(
 ID_LINGUE_ISO SERIAL NOT NULL,
 CODICE_ISO CHARACTER(2) NOT NULL,
 LINGUA CHARACTER VARYING(50) NOT NULL
)
;

-- ADD KEYS FOR TABLE LINGUE_ISO

ALTER TABLE LINGUE_ISO ADD CONSTRAINT PK_LINGUE_ISO PRIMARY KEY (ID_LINGUE_ISO)
;

ALTER TABLE LINGUE_ISO ADD CONSTRAINT K_LINGUE_ISO_2 UNIQUE (CODICE_ISO)
;

ALTER TABLE LINGUE_ISO ADD CONSTRAINT K_LINGUE_ISO_1 UNIQUE (ID_LINGUE_ISO)
;

-- TABLE MENU

CREATE TABLE MENU(
 ID_MENU SERIAL NOT NULL,
 ID_MENU_SUP INTEGER,
 ORDINE SMALLINT NOT NULL,
 ALIAS CHARACTER VARYING(50) NOT NULL,
 LINK CHARACTER VARYING(50) NOT NULL,
 ICON CHARACTER VARYING(50)
)
;

-- CREATE INDEXES FOR TABLE MENU

CREATE INDEX IDX_MENU_PK ON MENU (ID_MENU)
;

CREATE INDEX IDX_MENU_TREE ON MENU (ID_MENU_SUP)
;

-- ADD KEYS FOR TABLE MENU

ALTER TABLE MENU ADD CONSTRAINT PK_MENU PRIMARY KEY (ID_MENU)
;

ALTER TABLE MENU ADD CONSTRAINT K1_MENU UNIQUE (ID_MENU)
;

-- TABLE MENU_PROFILI

CREATE TABLE MENU_PROFILI(
 ID_MENU_PROFILI SERIAL NOT NULL,
 ID_MENU INTEGER NOT NULL,
 ID_PROFILO INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE MENU_PROFILI

CREATE INDEX IDX_MENU_PROFILI_FK ON MENU_PROFILI (ID_PROFILO,ID_MENU)
;

CREATE INDEX IDX_MENU_PROFILI_PK ON MENU_PROFILI (ID_MENU_PROFILI)
;

-- ADD KEYS FOR TABLE MENU_PROFILI

ALTER TABLE MENU_PROFILI ADD CONSTRAINT FK_MENU_PROFILI PRIMARY KEY (ID_MENU,ID_PROFILO,ID_MENU_PROFILI)
;

ALTER TABLE MENU_PROFILI ADD CONSTRAINT PK_MENU_PROFILI UNIQUE (ID_MENU_PROFILI)
;

-- TABLE MENU_LINGUE

CREATE TABLE MENU_LINGUE(
 ID_MENU_LINGUE SERIAL NOT NULL,
 ID_MENU INTEGER NOT NULL,
 ID_LINGUE_ISO INTEGER NOT NULL,
 DESCRIZIONE CHARACTER VARYING(50) NOT NULL
)
;

-- ADD KEYS FOR TABLE MENU_LINGUE

ALTER TABLE MENU_LINGUE ADD CONSTRAINT FK_MENU_LINGUE PRIMARY KEY (ID_MENU,ID_MENU_LINGUE,ID_LINGUE_ISO)
;

ALTER TABLE MENU_LINGUE ADD CONSTRAINT PK_MENU_LINGUE UNIQUE (ID_MENU_LINGUE)
;

-- TABLE UTENTI_PROFILI

CREATE TABLE UTENTI_PROFILI(
 ID_UTENTE_PROFILO SERIAL NOT NULL,
 ID_UTENTE INTEGER NOT NULL,
 ID_PROFILO INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE UTENTI_PROFILI

CREATE INDEX IDX_UTENTI_PROFILI_PK ON UTENTI_PROFILI (ID_UTENTE_PROFILO)
;

CREATE INDEX IDX_UTENTI_PROFILI_FK ON UTENTI_PROFILI (ID_PROFILO,ID_UTENTE)
;

-- ADD KEYS FOR TABLE UTENTI_PROFILI

ALTER TABLE UTENTI_PROFILI ADD CONSTRAINT PK_UTENTI_PROFILI PRIMARY KEY (ID_UTENTE,ID_PROFILO,ID_UTENTE_PROFILO)
;

ALTER TABLE UTENTI_PROFILI ADD CONSTRAINT K1_UTENTI_PROFILI UNIQUE (ID_UTENTE_PROFILO)
;

-- TABLE UTENTI_LINGUE

CREATE TABLE UTENTI_LINGUE(
 ID_UTENTI_LINGUE SERIAL NOT NULL,
 ID_UTENTE INTEGER NOT NULL,
 FL_DEFAULT BOOLEAN NOT NULL,
 ID_LINGUE_ISO INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE UTENTI_LINGUE

CREATE INDEX IDX_UTENTI_LINGUE_PK ON UTENTI_LINGUE (ID_UTENTI_LINGUE)
;

CREATE INDEX IDX_UTENTI_LINGUE_FK ON UTENTI_LINGUE (ID_UTENTE)
;

-- ADD KEYS FOR TABLE UTENTI_LINGUE

ALTER TABLE UTENTI_LINGUE ADD CONSTRAINT PK_UTENTI_LINGUE PRIMARY KEY (ID_UTENTE,ID_UTENTI_LINGUE,ID_LINGUE_ISO)
;

ALTER TABLE UTENTI_LINGUE ADD CONSTRAINT K1_UTENTI_LINGUE UNIQUE (ID_UTENTI_LINGUE)
;
-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 

ALTER TABLE MENU ADD CONSTRAINT RELATIONSHIP59 FOREIGN KEY (ID_MENU_SUP) REFERENCES MENU (ID_MENU) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE MENU_PROFILI ADD CONSTRAINT RELATIONSHIP15 FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE PASSWORD ADD CONSTRAINT RELATIONSHIP1 FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI (ID_UTENTE) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE MENU_PROFILI ADD CONSTRAINT RELATIONSHIP44 FOREIGN KEY (ID_PROFILO) REFERENCES PROFILI (ID_PROFILO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_PROFILI ADD CONSTRAINT RELATIONSHIP45 FOREIGN KEY (ID_PROFILO) REFERENCES PROFILI (ID_PROFILO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_PROFILI ADD CONSTRAINT RELATIONSHIP46 FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI (ID_UTENTE) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_LINGUE ADD CONSTRAINT RELATIONSHIP48 FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI (ID_UTENTE) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_LINGUE ADD CONSTRAINT RELATIONSHIP53 FOREIGN KEY (ID_LINGUE_ISO) REFERENCES LINGUE_ISO (ID_LINGUE_ISO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE MENU_LINGUE ADD CONSTRAINT REL_FK_LINGUE_ISO_TO_MENU_LINGUE FOREIGN KEY (ID_LINGUE_ISO) REFERENCES LINGUE_ISO (ID_LINGUE_ISO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE MENU_LINGUE ADD CONSTRAINT RELATIONSHIP58 FOREIGN KEY (ID_MENU) REFERENCES MENU (ID_MENU) ON DELETE CASCADE ON UPDATE NO ACTION
;




