/*
CREATED: 29/10/2017
MODIFIED: 17/12/2017
MODEL: AZIENDE_DIREZIONI_RICHIESTE_NEWS
DATABASE: POSTGRESQL 9.4
*/


-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE IF EXISTS NEWS CASCADE
;
DROP TABLE IF EXISTS NEWS_PROFILI CASCADE
;
DROP TABLE IF EXISTS NEWS_AZIENDE CASCADE
;
;
DROP TABLE IF EXISTS UTENTI_AZIENDE CASCADE
;
;
DROP TABLE IF EXISTS STAFF_DIREZIONI CASCADE
;
DROP TABLE IF EXISTS AZIENDE CASCADE
;
DROP TABLE IF EXISTS DIREZIONI CASCADE
;

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE DIREZIONI

CREATE TABLE DIREZIONI(
 ID_DIREZIONE SERIAL NOT NULL,
 ID_AZIENDA INTEGER NOT NULL,
 NOME_DIREZIONE CHARACTER VARYING(50) NOT NULL,
 NOME_DIREZIONE_BREVE CHARACTER VARYING(20) NOT NULL,
 ID_DIREZIONE_PARENT INTEGER
)
;

-- CREATE INDEXES FOR TABLE DIREZIONI

CREATE INDEX IDX_DIREZIONI_1 ON DIREZIONI (ID_DIREZIONE_PARENT)
;

-- ADD KEYS FOR TABLE DIREZIONI

ALTER TABLE DIREZIONI ADD CONSTRAINT PK_DIREZIONI PRIMARY KEY (ID_DIREZIONE,ID_AZIENDA)
;

ALTER TABLE DIREZIONI ADD CONSTRAINT ID_DIREZIONE UNIQUE (ID_DIREZIONE)
;

-- TABLE AZIENDE

CREATE TABLE AZIENDE(
 ID_AZIENDA SERIAL NOT NULL,
 ID_AZIENDA_PARENT INTEGER,
 CODICE CHARACTER VARYING(10) NOT NULL,
 RAGSOC CHARACTER VARYING(100) NOT NULL,
 PARTITA_IVA CHARACTER(11),
 CODICE_FISCALE CHARACTER(16),
 ALIAS_AZIENDA CHARACTER VARYING(50) NOT NULL,
 TIPO_AZIENDA CHARACTER VARYING(100)
)
;

-- CREATE INDEXES FOR TABLE AZIENDE

CREATE INDEX IDX_AZIENDE_1 ON AZIENDE (ID_AZIENDA_PARENT)
;

-- ADD KEYS FOR TABLE AZIENDE

ALTER TABLE AZIENDE ADD CONSTRAINT PK_AZIENDE PRIMARY KEY (ID_AZIENDA)
;

ALTER TABLE AZIENDE ADD CONSTRAINT ID_AZIENDA UNIQUE (ID_AZIENDA)
;

-- TABLE STAFF_DIREZIONI

CREATE TABLE STAFF_DIREZIONI(
 ID_STAFF_DIREZIONE SERIAL NOT NULL,
 ID_DIREZIONE INTEGER NOT NULL,
 ID_UTENTE_AZIENDA INTEGER NOT NULL
)
;

-- ADD KEYS FOR TABLE STAFF_DIREZIONI

ALTER TABLE STAFF_DIREZIONI ADD CONSTRAINT PK_PERSONALE_DIREZIONI PRIMARY KEY (ID_DIREZIONE,ID_STAFF_DIREZIONE,ID_UTENTE_AZIENDA)
;

ALTER TABLE STAFF_DIREZIONI ADD CONSTRAINT ID_PERSONALE_DIREZIONI UNIQUE (ID_STAFF_DIREZIONE)
;

-- TABLE UTENTI_AZIENDE

CREATE TABLE UTENTI_AZIENDE(
 ID_UTENTE_AZIENDA SERIAL NOT NULL,
 ID_UTENTE INTEGER NOT NULL,
 ID_AZIENDA INTEGER NOT NULL
)
;

-- ADD KEYS FOR TABLE UTENTI_AZIENDE

ALTER TABLE UTENTI_AZIENDE ADD CONSTRAINT FK_UTENTI_AZIENDE PRIMARY KEY (ID_UTENTE,ID_AZIENDA,ID_UTENTE_AZIENDA)
;

ALTER TABLE UTENTI_AZIENDE ADD CONSTRAINT K_ID_UTENTE_AZIENDA UNIQUE (ID_UTENTE_AZIENDA)
;


-- TABLE NEWS_AZIENDE

CREATE TABLE NEWS_AZIENDE(
 ID_NEWS_AZIENDA SERIAL NOT NULL,
 ID_NEWS INTEGER NOT NULL,
 ID_AZIENDA INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE NEWS_AZIENDE

CREATE INDEX IDX_NEWS_AZIENDE_FK ON NEWS_AZIENDE (ID_AZIENDA,ID_NEWS)
;

-- ADD KEYS FOR TABLE NEWS_AZIENDE

ALTER TABLE NEWS_AZIENDE ADD CONSTRAINT FK_NEWS_AZIENDE PRIMARY KEY (ID_NEWS,ID_AZIENDA,ID_NEWS_AZIENDA)
;

ALTER TABLE NEWS_AZIENDE ADD CONSTRAINT K_ID_NEWS_AZIENDA UNIQUE (ID_NEWS_AZIENDA)
;

-- TABLE NEWS_PROFILI

CREATE TABLE NEWS_PROFILI(
 ID_NEWS_PROFILO SERIAL NOT NULL,
 ID_NEWS INTEGER NOT NULL,
 ID_PROFILO INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE NEWS_PROFILI

CREATE INDEX IDX_NEWS_PROFILI_FK ON NEWS_PROFILI (ID_PROFILO,ID_NEWS)
;

-- ADD KEYS FOR TABLE NEWS_PROFILI

ALTER TABLE NEWS_PROFILI ADD CONSTRAINT FK_NEWS_PROFILI PRIMARY KEY (ID_NEWS,ID_PROFILO,ID_NEWS_PROFILO)
;

ALTER TABLE NEWS_PROFILI ADD CONSTRAINT PK_NEWS_PROFILI UNIQUE (ID_NEWS_PROFILO)
;

-- TABLE NEWS

CREATE TABLE NEWS(
 ID_NEWS SERIAL NOT NULL,
 TITOLO CHARACTER(250) NOT NULL,
 DT_VDAL CHARACTER(10) NOT NULL,
 DT_VAL CHARACTER(10) NOT NULL,
 DESCRIZIONE TEXT NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ICONA CHARACTER VARYING(100)
)
;

-- ADD KEYS FOR TABLE NEWS

ALTER TABLE NEWS ADD CONSTRAINT PK_NEWS PRIMARY KEY (ID_NEWS)
;

ALTER TABLE NEWS ADD CONSTRAINT K_NEWS_1 UNIQUE (ID_NEWS)
;
-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 



ALTER TABLE STAFF_DIREZIONI ADD CONSTRAINT REL_DIREZIONI_PRESONALE FOREIGN KEY (ID_DIREZIONE) REFERENCES DIREZIONI (ID_DIREZIONE) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE DIREZIONI ADD CONSTRAINT REL_AZIENDA_DIREZIONI FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE DIREZIONI ADD CONSTRAINT REL_ORGANIGRAMMA_AZIENDA FOREIGN KEY (ID_DIREZIONE_PARENT) REFERENCES DIREZIONI (ID_DIREZIONE) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_AZIENDE ADD CONSTRAINT RELATIONSHIP40 FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE CASCADE ON UPDATE NO ACTION
;



;

ALTER TABLE AZIENDE ADD CONSTRAINT RELATIONSHIP62 FOREIGN KEY (ID_AZIENDA_PARENT) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE NEWS_PROFILI ADD CONSTRAINT RELATIONSHIP64 FOREIGN KEY (ID_NEWS) REFERENCES NEWS (ID_NEWS) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE NEWS_AZIENDE ADD CONSTRAINT RELATIONSHIP65 FOREIGN KEY (ID_NEWS) REFERENCES NEWS (ID_NEWS) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE NEWS_AZIENDE ADD CONSTRAINT RELATIONSHIP66 FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE STAFF_DIREZIONI ADD CONSTRAINT RELATIONSHIP70 FOREIGN KEY (ID_UTENTE_AZIENDA) REFERENCES UTENTI_AZIENDE (ID_UTENTE_AZIENDA) ON DELETE NO ACTION ON UPDATE NO ACTION
;




