/*
CREATED: 22/10/2017
MODIFIED: 28/12/2017
MODEL: PDLWEB
DATABASE: POSTGRESQL 9.4
*/




-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE IF EXISTS PDL CASCADE
;
DROP TABLE IF EXISTS AREA_LAVORO CASCADE
;
DROP TABLE IF EXISTS EQUIPMENT CASCADE
;
DROP TABLE IF EXISTS PARAMETRI_AZIENDA CASCADE
;
DROP TABLE IF EXISTS UTENTI_IMPIANTI CASCADE
;
DROP TABLE IF EXISTS IMPIANTI CASCADE
;

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE IMPIANTI

CREATE TABLE IMPIANTI(
 ID_IMPIANTO SERIAL NOT NULL,
 ID_AZIENDA INTEGER NOT NULL,
 DESCR_IMPIANTO CHARACTER VARYING(50) NOT NULL,
 FILENAME_PLANIMETRIA CHARACTER VARYING(50),
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE IMPIANTI

ALTER TABLE IMPIANTI ADD CONSTRAINT PK_IMPIANTI PRIMARY KEY (ID_IMPIANTO,ID_AZIENDA)
;

ALTER TABLE IMPIANTI ADD CONSTRAINT K1_IMPIANTI UNIQUE (ID_IMPIANTO)
;

-- TABLE UTENTI_IMPIANTI

CREATE TABLE UTENTI_IMPIANTI(
 ID_UTENTE INTEGER NOT NULL,
 ID_IMPIANTO INTEGER NOT NULL
)
;

-- ADD KEYS FOR TABLE UTENTI_IMPIANTI

ALTER TABLE UTENTI_IMPIANTI ADD CONSTRAINT KEY1 PRIMARY KEY (ID_UTENTE,ID_IMPIANTO)
;

-- TABLE PARAMETRI_AZIENDA

CREATE TABLE PARAMETRI_AZIENDA(
 ID_PARAMETRO_AZIENDA SERIAL NOT NULL,
 ID_AZIENDA INTEGER NOT NULL,
 ID_PARAMETRO INTEGER NOT NULL
)
;

-- ADD KEYS FOR TABLE PARAMETRI_AZIENDA

ALTER TABLE PARAMETRI_AZIENDA ADD CONSTRAINT PK_PARAMETRI_AZIENDA PRIMARY KEY (ID_AZIENDA,ID_PARAMETRO,ID_PARAMETRO_AZIENDA)
;

ALTER TABLE PARAMETRI_AZIENDA ADD CONSTRAINT K1_PARAMETRI_AZIENDA UNIQUE (ID_PARAMETRO_AZIENDA)
;

-- TABLE EQUIPMENT

CREATE TABLE EQUIPMENT(
 ID_EQUIPMENT SERIAL NOT NULL,
 ID_AREA INTEGER NOT NULL,
 DESCR_EQUIPMENT CHARACTER VARYING(100) NOT NULL,
 FL_EIS BOOLEAN DEFAULT FALSE NOT NULL,
 NOTE TEXT
)
;

-- ADD KEYS FOR TABLE EQUIPMENT

ALTER TABLE EQUIPMENT ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (ID_EQUIPMENT,ID_AREA)
;

ALTER TABLE EQUIPMENT ADD CONSTRAINT K1_EQUIPMENT UNIQUE (ID_EQUIPMENT)
;

-- TABLE AREA_LAVORO

CREATE TABLE AREA_LAVORO(
 ID_AREA SERIAL NOT NULL,
 ID_IMPIANTO INTEGER NOT NULL,
 DESCR_AREA CHARACTER VARYING(30) NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE AREA_LAVORO

ALTER TABLE AREA_LAVORO ADD CONSTRAINT PK_AREA_LAVORO PRIMARY KEY (ID_AREA,ID_IMPIANTO)
;

ALTER TABLE AREA_LAVORO ADD CONSTRAINT K1_AREA_LAVORO UNIQUE (ID_AREA)
;

-- TABLE PDL

CREATE TABLE PDL(
 ID_PDL SERIAL NOT NULL,
 ID_AZIENDA INTEGER NOT NULL,
 ID_IMPIANTO INTEGER NOT NULL,
 ID_AREA INTEGER NOT NULL,
 ID_EQUIPMENT INTEGER NOT NULL,
 NR_PDL CHARACTER VARYING(20) NOT NULL,
 DT_PDL CHARACTER(10) NOT NULL,
 STATO CHARACTER(3) NOT NULL,
 DESCRIZIONE_LAVORO TEXT NOT NULL,
 TS_INS TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
 ID_UTENTE_INS INTEGER NOT NULL,
 TS_DEL TIMESTAMP,
 ID_UTENTE_DEL INTEGER
)
;

-- ADD KEYS FOR TABLE PDL

ALTER TABLE PDL ADD CONSTRAINT PK_PDL PRIMARY KEY (ID_PDL,ID_EQUIPMENT,ID_AREA,ID_IMPIANTO,ID_AZIENDA)
;

ALTER TABLE PDL ADD CONSTRAINT K1_PDL UNIQUE (ID_PDL)
;
-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION ------------------------------------------------- 

ALTER TABLE IMPIANTI ADD CONSTRAINT FK_IMPIANTI FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_IMPIANTI ADD CONSTRAINT FK1_UTENTI_IMPIANTI FOREIGN KEY (ID_UTENTE) REFERENCES UTENTI (ID_UTENTE) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE UTENTI_IMPIANTI ADD CONSTRAINT FK2_UTENTI_IMPIANTI FOREIGN KEY (ID_IMPIANTO) REFERENCES IMPIANTI (ID_IMPIANTO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE PARAMETRI_AZIENDA ADD CONSTRAINT FK2_PARAMETRI_AZIENDA FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE PARAMETRI_AZIENDA ADD CONSTRAINT FK1_PARAMETRI_AZIENDA FOREIGN KEY (ID_PARAMETRO) REFERENCES PARAMETRI (ID_PARAMETRO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE AREA_LAVORO ADD CONSTRAINT FK_AREA_LAVORO FOREIGN KEY (ID_IMPIANTO) REFERENCES IMPIANTI (ID_IMPIANTO) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE EQUIPMENT ADD CONSTRAINT FK_EQUIPMENT FOREIGN KEY (ID_AREA) REFERENCES AREA_LAVORO (ID_AREA) ON DELETE CASCADE ON UPDATE NO ACTION
;

ALTER TABLE PDL ADD CONSTRAINT FK_PDL_IMPIANTO FOREIGN KEY (ID_IMPIANTO) REFERENCES IMPIANTI (ID_IMPIANTO) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PDL ADD CONSTRAINT FK_PDL_AREA FOREIGN KEY (ID_AREA) REFERENCES AREA_LAVORO (ID_AREA) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PDL ADD CONSTRAINT FK_PDL_EQUIPMENT FOREIGN KEY (ID_EQUIPMENT) REFERENCES EQUIPMENT (ID_EQUIPMENT) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE PDL ADD CONSTRAINT FK_PDL_SITO FOREIGN KEY (ID_AZIENDA) REFERENCES AZIENDE (ID_AZIENDA) ON DELETE NO ACTION ON UPDATE NO ACTION
;




