-- Drop views 

drop VIEW if exists V_UTENTI_PROFILI cascade;
DROP VIEW IF exists v_menu CASCADE;
DROP VIEW IF exists v_menu_tree;
DROP VIEW IF exists V_AZIENDE_TREE;
DROP VIEW IF exists V_DIPENDENTI;
DROP VIEW IF exists V_UTENTI;
DROP VIEW IF exists V_LOGIN;




-- view V_UTENTI_PROFILI
CREATE VIEW V_UTENTI_PROFILI 
AS
SELECT
	UPR.ID_UTENTE
	,PRF.CODICE
	,PRF.DESCRIZIONE
FROM UTENTI_PROFILI AS UPR
LEFT OUTER JOIN PROFILI AS PRF
ON UPR.ID_PROFILO = PRF.ID_PROFILO
;


-- view V_MENU
CREATE VIEW V_MENU AS 
 SELECT me.id_menu,
    me.id_menu_sup,
	me.alias,
    me.ordine,
    ml.descrizione,
    LI.codice_iso,
    me.link,
	me.icon
   FROM menu me
   INNER JOIN menu_lingue AS ML 
   ON me.id_menu = ml.id_menu
   INNER JOIN LINGUE_ISO AS LI
   ON ML.ID_LINGUE_ISO=LI.ID_LINGUE_ISO
;


-- view v_menu_tree
CREATE VIEW v_menu_tree AS 
WITH RECURSIVE v_menu_tree(
	id_menu_sup
	,descrizione_sup
	,link_sup
	,id_menu
	,alias
	,icon
	,descrizione
	,link
	,path
	,path_descri
	,link_chain
	,depth
	,codice_iso) AS (
	SELECT 
		r.id_menu_sup
		,p1.descrizione AS descrizione_sup
		,p1.link AS link_sup
		,r.id_menu
		,R.ALIAS 
		,R.ICON
		,p2.descrizione
		,p2.link
		,lpad(r.ordine::varchar, 4, '0') AS path
		,'Home / ' || r.descrizione::varchar AS path_descri
	        ,'astro?FUNCTIONID=Home;' || P2.LINK  as LINK_CHAIN		
        	,1 as DEPTH
		,r.codice_iso
	FROM v_menu as r
		,v_menu as p1
		,v_menu as p2
	WHERE r.id_menu_sup = (SELECT id_menu FROM menu WHERE id_menu_sup IS NULL) 
		AND p1.id_menu = r.id_menu_sup AND p1.codice_iso = r.codice_iso 
		AND p2.id_menu = r.id_menu AND p2.codice_iso = r.codice_iso 
		AND p1.codice_iso = p2.codice_iso
	UNION ALL
	SELECT 
		r.id_menu_sup
		,p1.descrizione AS descrizione_sup
		,p1.link AS link_sup
		,r.id_menu
		,R.ALIAS
		,R.ICON
		,p2.descrizione
		,p2.link
		,nd.path || lpad(r.ordine::varchar, 4, '0') as path
		,nd.path_descri|| ' / ' || r.descrizione AS path_descri
        	,LINK_CHAIN || ';' || P2.LINK  as LINK_CHAIN
		,nd.depth + 1
		,r.codice_iso
	FROM v_menu as r
		,v_menu as p1
		,v_menu as p2
		,v_menu_tree as nd
	WHERE 
		R.ID_MENU_SUP not in (SELECT ID_MENU FROM V_MENU WHERE ID_MENU_SUP IS  NULL) 
		and r.id_menu_sup = nd.id_menu AND r.codice_iso = nd.codice_iso 
		AND p1.id_menu = r.id_menu_sup AND p1.codice_iso = r.codice_iso 
		AND p2.id_menu = r.id_menu AND p2.codice_iso = r.codice_iso
)
SELECT DISTINCT * FROM v_menu_tree
UNION ALL
SELECT id_menu_sup
	,'' AS descrizione_sup
	,'' AS link_sup
	,id_menu
	,'Home' AS ALIAS
	,'fa fa-home' AS ICON
	,descrizione
	,link
	,'' AS path
	,'Home' AS path_descri
	,'astro?FUNCTIONID=Home' AS LINK_CHAIN
    	,0 AS depth
    	,codice_iso
FROM v_menu 
WHERE id_menu_sup IS NULL
;



-- view V_AZIENDE_TREE
CREATE VIEW V_AZIENDE_TREE AS 
WITH RECURSIVE V_AZIENDE_TREE(
		ID_AZIENDA_PARENT
		, RAGSOC_SUP
		, ID_AZIENDA
		, ALIAS_AZIENDA
		, RAGSOC
		, PATH
		, DEPTH
	) as (
	SELECT
		ID_AZIENDA_PARENT
		, ''::varchar AS RAGSOC_SUP
		, ID_AZIENDA
		, ALIAS_AZIENDA
		, RAGSOC
		, LPAD(ID_AZIENDA::varchar, 5, '0') as PATH
		, 0 AS DEPTH
		, TIPO_AZIENDA
		, CODICE
	FROM AZIENDE WHERE ID_AZIENDA_PARENT IS NULL
    UNION ALL
    SELECT
        R.ID_AZIENDA_PARENT, 
        P1.RAGSOC::varchar AS RAGSOC_SUP,
        R.ID_AZIENDA, 
		R.ALIAS_AZIENDA ,
        P2.RAGSOC,
        PATH || '>' || LPAD(R.ID_AZIENDA::varchar, 5, '0') as PATH, 
        ND.DEPTH + 1
        , R.TIPO_AZIENDA
		, R.CODICE
    FROM AZIENDE AS R
		,AZIENDE AS P1
		,AZIENDE AS P2,
        V_AZIENDE_TREE AS ND
    WHERE R.ID_AZIENDA_PARENT IS NOT NULL
	AND R.ID_AZIENDA_PARENT = ND.ID_AZIENDA 
    AND P1.ID_AZIENDA = R.ID_AZIENDA_PARENT AND P2.ID_AZIENDA = R.ID_AZIENDA 
)
SELECT DISTINCT * FROM V_AZIENDE_TREE
;



-- view [V_UTENTI]
CREATE VIEW V_UTENTI AS
SELECT 	USR.ID_UTENTE 
	,USR.USERNAME 
	,LI.CODICE_ISO 
	,USR.COGNOME AS COGNOME_UTENTE 
	,USR.NOME AS NOME_UTENTE 
	,USR.NOME || ' ' || USR.COGNOME AS NOME_COGNOME
	,USR.EMAIL 
	,USR.FL_DISATTIVO 
	,USR.TS_LOGIN
	,to_char(ts_login,'yyyy/mm/dd') as DATA_ULTIMO_ACCESSO 
	,to_char(ts_login,'HH24:MI:SS') as ORA_ULTIMO_ACCESSO 	
	,PWD.PASSWORD 
	,PWD.DT_SCADENZA 
	,(SELECT string_agg(CODICE, ',') FROM V_UTENTI_PROFILI AS EF WHERE ID_UTENTE=USR.ID_UTENTE ) AS PROFILO
	,(SELECT string_agg(DESCRIZIONE, ',') FROM V_UTENTI_PROFILI AS EF WHERE ID_UTENTE=USR.ID_UTENTE ) AS DESCRIZIONE_PROFILO
	,(SELECT string_agg(UA.ID_AZIENDA::varchar, ',') FROM UTENTI_AZIENDE AS UA WHERE UA.ID_UTENTE=USR.ID_UTENTE) AS AZIENDE_UTENTE
	
	,(SELECT string_agg(AZ.RAGSOC, ',') 
		FROM UTENTI_AZIENDE AS UA
		INNER JOIN AZIENDE AS AZ
		ON UA.ID_AZIENDA=AZ.ID_AZIENDA
		WHERE UA.ID_UTENTE=USR.ID_UTENTE 
		) AS RAGSOC_AZIENDE_UTENTE

	,(SELECT string_agg(SD.ID_DIREZIONE::varchar, ',') 
		FROM STAFF_DIREZIONI AS SD
		INNER JOIN UTENTI_AZIENDE AS UA 
		ON UA.ID_UTENTE_AZIENDA=SD.ID_UTENTE_AZIENDA 
		) AS LISTA_DIREZIONI


FROM UTENTI AS USR  
LEFT OUTER JOIN PASSWORD AS PWD  
ON USR.ID_UTENTE=PWD.ID_UTENTE AND PWD.FL_VALIDA=true 
INNER JOIN UTENTI_LINGUE AS UL 
ON USR.ID_UTENTE =UL.ID_UTENTE AND UL.FL_DEFAULT=true
INNER JOIN LINGUE_ISO AS LI 
ON UL.ID_LINGUE_ISO =LI.ID_LINGUE_ISO
;


-- view [V_LOGIN]
CREATE VIEW V_LOGIN
AS
SELECT 	USR.ID_UTENTE 
	,USR.USERNAME 
	,LI.CODICE_ISO 
	,USR.COGNOME AS COGNOME_UTENTE 
	,USR.NOME AS NOME_UTENTE 
	,PWD.PASSWORD 
	,PWD.DT_SCADENZA 

	,(SELECT string_agg(rtrim(CODICE), ',') 
		FROM V_UTENTI_PROFILI 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS PROFILO  

	,(SELECT string_agg(DESCRIZIONE, ',') 
		FROM V_UTENTI_PROFILI 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS DESCRIZIONE_PROFILO  


	,(SELECT string_agg(ID_AZIENDA::varchar, ',') 
		FROM UTENTI_AZIENDE 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS AZIENDE_UTENTE  


	,( SELECT ALIAS_AZIENDA FROM V_AZIENDE_TREE WHERE ID_AZIENDA IN (
			SELECT ID_AZIENDA 
			FROM UTENTI_AZIENDE AS UA 
			LEFT OUTER JOIN UTENTI AS UT 
			ON UA.ID_UTENTE=UT.ID_UTENTE 
			WHERE LOWER(UT.USERNAME)=LOWER(USR.USERNAME)) ORDER BY PATH limit 1 ) AS ALIAS_AZIENDA_UTENTE 
			
	,( SELECT AZ.CODICE 
			FROM V_AZIENDE_TREE AS AT 
			LEFT OUTER JOIN AZIENDE AS AZ 
			ON AZ.ID_AZIENDA = AT.ID_AZIENDA 
			WHERE AT.ID_AZIENDA IN (
			SELECT ID_AZIENDA 
			FROM UTENTI_AZIENDE AS UA 
			LEFT OUTER JOIN UTENTI AS UT 
			ON UA.ID_UTENTE=UT.ID_UTENTE 
			WHERE LOWER(UT.USERNAME)=LOWER(USR.USERNAME)) ORDER BY PATH limit 1 ) AS CODICE_AZIENDA_UTENTE 

	,(SELECT string_agg(SD.ID_DIREZIONE::varchar, ',') 
		FROM STAFF_DIREZIONI AS SD
		INNER JOIN UTENTI_AZIENDE AS UA 
		ON UA.ID_UTENTE_AZIENDA=SD.ID_UTENTE_AZIENDA 
		) AS DIREZIONI_UTENTE
		
FROM UTENTI AS USR  
LEFT OUTER JOIN PASSWORD AS PWD  
ON USR.ID_UTENTE=PWD.ID_UTENTE AND PWD.FL_VALIDA=true 
INNER JOIN UTENTI_LINGUE AS UL 
ON USR.ID_UTENTE =UL.ID_UTENTE AND UL.FL_DEFAULT=true
INNER JOIN LINGUE_ISO AS LI 
ON LI.ID_LINGUE_ISO =UL.ID_LINGUE_ISO  
;



-- view [V_PARAMETRI]
DROP VIEW IF exists V_PARAMETRI CASCADE;

CREATE VIEW V_PARAMETRI
AS
	select  
		PAR.*
		,DOM.DESCRIZIONE AS DESCR_DOMINIO
	FROM PARAMETRI AS PAR 
	INNER JOIN PARAMETRI AS DOM
	ON PAR.DOMINIO=DOM.CODICE AND DOM.DOMINIO ='DOM'
;


-- view [V_FAMIGLIA_PRODOTTI_GAS]
DROP VIEW IF exists V_FAMIGLIA_PRODOTTI_GAS;

CREATE VIEW V_FAMIGLIA_PRODOTTI_GAS
AS
	select
		''::char(1) as EMPTY_FIELD
		,PG.*
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PG.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PG.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from FAMIGLIA_PRODOTTI_GAS AS PG
	left outer join UTENTI AS UT
	ON PG.ID_UTENTE_INS = UT.ID_UTENTE
;



-- view [V_PRODOTTI_GAS_COMP]
DROP VIEW IF exists V_PRODOTTI_GAS_COMP;

CREATE VIEW V_PRODOTTI_GAS_COMP
AS
	select
		PGC.*
		,GAS.DESCRIZIONE AS DESCR_COMPONENTE
		,STR.DESCRIZIONE AS DESCR_STRUMENTO_ANALISI
		,FQA.DESCRIZIONE AS DESCR_FREQUENZA_ANALISI
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PGC.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PGC.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from PRODOTTI_GAS_COMP AS PGC
	left outer join V_PARAMETRI AS GAS
	ON PGC.CODICE_COMPONENTE = GAS.CODICE AND GAS.DOMINIO='GAS'
	left outer join V_PARAMETRI AS STR
	ON PGC.CODICE_STRUMENTO_ANALISI = STR.CODICE AND STR.DOMINIO='STR'
	left outer join V_PARAMETRI AS FQA
	ON PGC.CODICE_FREQUENZA_ANALISI = FQA.CODICE AND FQA.DOMINIO='FQA'
	left outer join UTENTI AS UT
	ON PGC.ID_UTENTE_INS = UT.ID_UTENTE
;


-- view [V_IMPUREZZE_GARANTITE]
DROP VIEW IF exists V_IMPUREZZE_GARANTITE;

CREATE VIEW V_IMPUREZZE_GARANTITE
AS
	select
		IMG.*
		,IMP.DESCRIZIONE AS DESCR_IMPUREZZA
		,STR.DESCRIZIONE AS DESCR_STRUMENTO_ANALISI
		,FQA.DESCRIZIONE AS DESCR_FREQUENZA_ANALISI
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(IMG.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(IMG.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from IMPUREZZE_GARANTITE AS IMG
	left outer join V_PARAMETRI AS IMP
	ON IMG.CODICE_IMPUREZZA = IMP.CODICE AND IMP.DOMINIO='IMP'
	left outer join V_PARAMETRI AS STR
	ON IMG.CODICE_STRUMENTO_ANALISI = STR.CODICE AND STR.DOMINIO='STR'
	left outer join V_PARAMETRI AS FQA
	ON IMG.CODICE_FREQUENZA_ANALISI = FQA.CODICE AND FQA.DOMINIO='FQA'
	left outer join UTENTI AS UT
	ON IMG.ID_UTENTE_INS = UT.ID_UTENTE
;


-- view [V_PRODOTTI_GAS]
DROP VIEW IF exists V_PRODOTTI_GAS;

CREATE VIEW V_PRODOTTI_GAS
AS
	select
		PGS.*
		,FAM.DESCRIZIONE AS DESCR_FAMIGLIA_ALLESTIMENTO
		,ALS.DESCRIZIONE AS DESCR_ALLESTIMENTO
		,ADR.DESCRIZIONE AS DESCR_ETICHETTA_ADR
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PGS.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PGS.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from PRODOTTI_GAS AS PGS
	left outer join V_PARAMETRI AS FAM
	ON PGS.CODICE_FAMIGLIA_ALLESTIMENTO = FAM.CODICE AND FAM.DOMINIO='FAM'
	left outer join V_PARAMETRI AS ALS
	ON PGS.CODICE_ALLESTIMENTO = ALS.CODICE AND ALS.DOMINIO='ALS'
	left outer join V_PARAMETRI AS ADR
	ON PGS.CODICE_ETICHETTA_ADR = ADR.CODICE AND ADR.DOMINIO='ADR'
	left outer join UTENTI AS UT
	ON PGS.ID_UTENTE_INS = UT.ID_UTENTE
;



-- view [V_DETTAGLIO_PRODOTTI]
DROP VIEW IF exists V_DETTAGLIO_PRODOTTI;

CREATE VIEW V_DETTAGLIO_PRODOTTI
AS

select 
	pg.id_prodotti_gas
	,fpg.id_famiglia
	,fpg.codice_famiglia
	,fpg.nome_commerciale
	,(SELECT string_agg(descr_componente, ',') FROM v_prodotti_gas_comp as pgc where pgc.id_famiglia=pg.id_famiglia) as composizione
	,pg.descr_famiglia_allestimento
	,pg.codice_prodotto
	,pg.descrizione_prodotto 
	,pg.codice_sap_etichetta
	,pg.codice_allestimento
	,pg.descr_allestimento
from v_prodotti_gas as pg	
inner join famiglia_prodotti_gas as fpg
on pg.id_famiglia=fpg.id_famiglia
;




-- view [V_SPECIFICHE_ALLESTIMENTI]
DROP VIEW IF exists V_SPECIFICHE_ALLESTIMENTI;

CREATE VIEW V_SPECIFICHE_ALLESTIMENTI
AS

select 
 SA.ID_SPECIFICA
 ,SA.ID_FAMIGLIA 
 ,AL.ID_ALLESTIMENTO
 ,AL.ORDINE
 ,ALS.CODICE AS CODICE_ALLESTIMENTO
 ,ALS.DESCRIZIONE AS TIPOLOGIA_ALLESTIMENTO
 ,AL.CARATTERISTICA AS CARATTERISTICA
 ,COALESCE(SA.DESCRIZIONE,'-') as DESCRIZIONE
 ,AL.FL_MATERIALE
 ,SA.ID_MATERIALE
 ,MAT.DESCRIZIONE AS DESCRIZIONE_MATERIALE
 ,MAT.CODICE_SAP
from ALLESTIMENTI as AL
LEFT OUTER join SPECIFICHE_ALLESTIMENTO as SA
ON AL.ID_ALLESTIMENTO = SA.ID_ALLESTIMENTO
LEFT OUTER JOIN FAMIGLIA_PRODOTTI_GAS AS FPG
ON FPG.ID_FAMIGLIA=SA.ID_FAMIGLIA 
LEFT OUTER JOIN PARAMETRI AS ALS 
ON ALS.CODICE = AL.CODICE_ALLESTIMENTO AND ALS.DOMINIO='ALS'
LEFT OUTER JOIN MATERIALI AS MAT 
ON SA.ID_MATERIALE = MAT.ID_MATERIALE 
;



-- view [V_ALLESTIMENTI]
DROP VIEW IF exists V_ALLESTIMENTI;

CREATE VIEW V_ALLESTIMENTI
AS

select 
 AL.*
 ,ALS.DESCRIZIONE AS DESCR_ALLESTIMENTO
from ALLESTIMENTI as AL
INNER JOIN PARAMETRI AS ALS 
ON ALS.CODICE = AL.CODICE_ALLESTIMENTO AND ALS.DOMINIO='ALS'
;


-- view [V_MATERIALI]
DROP VIEW IF exists V_MATERIALI;

CREATE VIEW V_MATERIALI
AS

select 
	*
	,DESCRIZIONE || ' - ' || CODICE_SAP AS DESCRIZIONE_E_CODICE_SAP
from MATERIALI
;

-- view [V_SITIQHSE]
DROP VIEW IF exists V_SITIQHSE;

CREATE VIEW V_SITIQHSE
AS
SELECT AZI.* 
	,coalesce(ATA.valore_attributo,'N') as sito_aifa
FROM AZIENDE AS AZI
left outer join ATTRIBUTI_AZIENDA as ATA on AZI.id_azienda = ATA.id_azienda and ATA.codice_attributo='SITO_AIFA'
WHERE TIPO_AZIENDA LIKE '%HSE%'
;



-- view [V_ALIMOD20]
DROP VIEW IF exists V_ALIMOD20_MASTER;
DROP VIEW IF exists V_ALIMOD20;
DROP VIEW IF exists V_ALIMOD20_DETTAGLIO;

CREATE VIEW V_ALIMOD20
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
		,coalesce(chk.conta,0) as NR_CHK
		,coalesce(clo.conta,0) as NR_CLO
		,coalesce(clo.conta,0)+coalesce(chk.conta,0)  AS NR_AZIONI_CLO
		,coalesce(tot.conta,0) AS NR_AZIONI_TOT
	FROM ALIMOD20 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
	left outer join (select count(*) as conta, id_modulo from ALIMOD20_dettagli where stato_azione='CHK' group by id_modulo ) as chk
	on chk.id_modulo = mod.id_modulo
	left outer join (select count(*) as conta, id_modulo from ALIMOD20_dettagli where stato_azione='CLO' group by id_modulo ) as clo
	on clo.id_modulo = mod.id_modulo
	left outer join (select count(*) as conta, id_modulo from ALIMOD20_dettagli group by id_modulo ) as tot
	on tot.id_modulo = mod.id_modulo
;

-- view [V_ALIMOD20_DETTAGLIO]

CREATE VIEW V_ALIMOD20_DETTAGLIO
AS
SELECT 
	DET.* 
	,'' as NUMERO_AZIONE
	,'' as PERC_AVANZAMENTO
	,SAZ.DESCRIZIONE AS DESCR_STATO_AZIONE
	,CLA.DESCRIZIONE AS DESCR_CLASSIFICAZIONE
	,ACT.DESCRIZIONE AS DESCR_TIPO_AZIONE
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
	,RES.NOME || ' ' || RES.COGNOME AS NOME_COGNOME_RES
FROM ALIMOD20_DETTAGLI AS DET
LEFT OUTER JOIN PARAMETRI AS SAZ
ON SAZ.CODICE=DET.STATO_AZIONE AND SAZ.DOMINIO = 'SAZ'
LEFT OUTER JOIN PARAMETRI AS CLA
ON CLA.CODICE=DET.CODICE_CLASSIFICAZIONE AND CLA.DOMINIO = 'CLA'
LEFT OUTER JOIN PARAMETRI AS ACT
ON ACT.CODICE=DET.CODICE_TIPO_AZIONE AND ACT.DOMINIO = 'ACT'
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
LEFT OUTER JOIN UTENTI AS RES
ON RES.ID_UTENTE=DET.ID_UTENTE_RES 
;

	

-- view [V_ALIMOD20_MASTER]
CREATE VIEW V_ALIMOD20_MASTER
AS
select
	codice_bl
	,tt.id_azienda
	,nome_cognome_res
	,descr_sito
	,descr_bl
	,nr_modulo
	,nr_dettaglio
	,act.descrizione as tipo_azione
	,dd.descrizione
	,tt.dt_modulo
	,dd.dt_chiusura
	,dd.dt_scadenza
	,dd.descr_stato_azione
from V_ALIMOD20_DETTAGLIO as dd
inner join V_alimod20 as tt on tt.id_modulo=dd.id_modulo
left outer join v_parametri as act on act.dominio='ACT' and act.codice = dd.codice_tipo_azione
;


-- view V_REPORT_ALIMOD20
DROP VIEW IF EXISTS V_REPORT_ALIMOD20;
CREATE VIEW V_REPORT_ALIMOD20 
AS

select
	t1.*
	, round(nr_azioni_chiuse::numeric/nr_azioni_registrate::numeric* 100,0) as perc_chiuse_registrate
	, case when nr_azioni_aperte>0 then  round(nr_azioni_scadute::numeric/nr_azioni_aperte::numeric* 100,0) else 0 end as perc_scadute_aperte
from (
select 
	descr_bl
	,id_azienda
	,descr_sito
	,count(*) as nr_azioni_registrate
	,sum(case when descr_stato_azione='Aperta' then 1 else 0 end) as nr_azioni_aperte
	,sum(case when descr_stato_azione='Completata' or descr_stato_azione='Verificata' then 1 else 0 end) as nr_azioni_chiuse
	,sum(case when dt_chiusura is not null and dt_chiusura!='' and (dt_chiusura ::date +interval '30 day' > dt_scadenza::date)  then 1 else 0 end ) as nr_azioni_chiuse_ritardo
	,sum(case when (dt_chiusura is null OR dt_chiusura='') and (CURRENT_DATE ::date +interval '30 day' > dt_scadenza::date)  then 1 else 0 end ) as nr_azioni_scadute
from v_alimod20_master
group by 
	descr_bl
	,id_azienda	
	,descr_sito
) as t1
;

-- view [V_ALIMOD50]
DROP VIEW IF exists V_ALIMOD50;

CREATE VIEW V_ALIMOD50
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,VER.DESCRIZIONE AS DESCR_TIPO_VERIFICA
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM ALIMOD50 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	LEFT OUTER JOIN PARAMETRI AS VER
	ON VER.CODICE=MOD.CODICE_TIPO_VERIFICA AND VER.DOMINIO = 'VER'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;


-- view [V_ALIMOD51]
DROP VIEW IF exists V_ALIMOD51;

CREATE VIEW V_ALIMOD51
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM ALIMOD51 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;



-- view [V_ALIMOD52]
DROP VIEW IF exists V_ALIMOD52;

CREATE VIEW V_ALIMOD52
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
		,CASE
		  WHEN (MESE ='01') THEN 'Gennaio'
		  WHEN (MESE ='02') THEN 'Febbraio'
		  WHEN (MESE ='03') THEN 'Marzo'
		  WHEN (MESE ='04') THEN 'Aprile'
		  WHEN (MESE ='05') THEN 'Maggio'
		  WHEN (MESE ='06') THEN 'Giugno'
		  WHEN (MESE ='07') THEN 'Luglio'
		  WHEN (MESE ='08') THEN 'Agosto'
		  WHEN (MESE ='09') THEN 'Settembre'
		  WHEN (MESE ='10') THEN 'Ottobre'
		  WHEN (MESE ='11') THEN 'Novembre'
		  WHEN (MESE ='12') THEN 'Dicembre'
		  ELSE ''
		END AS DESCR_MESE
	FROM ALIMOD52 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;


-- view [V_ALIMOD80]
DROP VIEW IF exists V_ALIMOD80;

CREATE VIEW V_ALIMOD80
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
		,TIM.DESCRIZIONE AS DESCR_TIPO_IMPIANTO
		,NEV.DESCRIZIONE AS DESCR_NATURA_EVENTO
		,PPE.DESCRIZIONE AS DESCR_PRODOTTO_PERTINENTE
		,RCA.DESCRIZIONE AS DESCR_ALBERO_CAUSE
		,CPR1.DESCRIZIONE AS DESCR_CATEGORIA_PRINCIPALE
		,CSE1.DESCRIZIONE AS DESCR_SOTTOCATEGORIA_PRINCIPALE
		,CPR2.DESCRIZIONE AS DESCR_CATEGORIA_SECONDARIA
		,CSE2.DESCRIZIONE AS DESCR_SOTTOCATEGORIA_SECONDARIA
		,ATI.DESCRIZIONE AS DESCR_AFF_ATTREZZATURA_INTERESSATA
		,CAI.DESCRIZIONE AS DESCR_AFF_COMP_ATTR_INTERESSATA
		,EUR.DESCRIZIONE AS DESCR_COSTI_EURO
		,INL.DESCRIZIONE AS DESCR_LIVELLO_INCIDENTE
		,CLI.DESCRIZIONE AS DESCR_CLIENTE
		,PCO.DESCRIZIONE AS DESCR_PARTE_INTERESSATA
		,PPE2.DESCRIZIONE AS DESCR_PRODOTTO_RILASCIATO
		,INL2.DESCRIZIONE AS DESCR_LIVELLO_INCIDENTE_2
		,PCO2.DESCRIZIONE AS DESCR_PARTE_INTERESSATA_PCO2
		,OOE2.DESCRIZIONE AS DESCR_ORA_LOCALE
		,MME2.DESCRIZIONE AS DESCR_MIN_LOCALE
		,GGE.DESCRIZIONE AS DESCR_GIORNI_EVENTO
		,OOE.DESCRIZIONE AS DESCR_ORA_EVENTO
		,MME.DESCRIZIONE AS DESCR_MIN_EVENTO
		,UNI1.DESCRIZIONE AS DESCR_UNITA_RILASCIATA
		,UNI2.DESCRIZIONE AS DESCR_UNITA_MAX_PERMESSA
	FROM ALIMOD80 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
	LEFT OUTER JOIN PARAMETRI AS TIM
	ON TIM.CODICE = MOD.CODICE_TIPO_IMPIANTO AND TIM.DOMINIO ='TIM'
	LEFT OUTER JOIN PARAMETRI AS NEV
	ON NEV.CODICE = MOD.CODICE_NATURA_EVENTO AND NEV.DOMINIO ='NEV'
	LEFT OUTER JOIN PARAMETRI AS PPE
	ON PPE.CODICE = MOD.CODICE_PRODOTTO_PERTINENTE AND PPE.DOMINIO ='PPE'
	LEFT OUTER JOIN PARAMETRI AS RCA
	ON RCA.CODICE = MOD.ALBERO_CAUSE AND RCA.DOMINIO ='RCA'
	LEFT OUTER JOIN PARAMETRI AS CPR1
	ON CPR1.CODICE = MOD.CATEGORIA_PRINCIPALE AND CPR1.DOMINIO ='CPR'
	LEFT OUTER JOIN PARAMETRI AS CSE1
	ON CSE1.CODICE = MOD.SOTTOCATEGORIA_PRINCIPALE AND CSE1.DOMINIO ='CSE'
	LEFT OUTER JOIN PARAMETRI AS CPR2
	ON CPR2.CODICE = MOD.CATEGORIA_SECONDARIA AND CPR2.DOMINIO ='CPR'
	LEFT OUTER JOIN PARAMETRI AS CSE2
	ON CSE2.CODICE = MOD.SOTTOCATEGORIA_SECONDARIA AND CSE2.DOMINIO ='CSE'
	LEFT OUTER JOIN PARAMETRI AS ATI
		ON MOD.CODICE_AFF_ATTREZZATURA_INTERESSATA = ATI.CODICE AND ATI.DOMINIO ='ATI'
	LEFT OUTER JOIN PARAMETRI AS CAI
		ON MOD.CODICE_AFF_COMP_ATTR_INTERESSATA = CAI.CODICE AND CAI.DOMINIO ='CAI'
	LEFT OUTER JOIN PARAMETRI AS EUR
		ON MOD.CODICE_COSTI_EURO = EUR.CODICE AND EUR.DOMINIO ='EUR'
	LEFT OUTER JOIN PARAMETRI AS INL
		ON MOD.CODICE_LIVELLO_INCIDENTE =INL.CODICE AND INL.DOMINIO ='INL'
	LEFT OUTER JOIN PARAMETRI AS CLI
		ON MOD.CODICE_CLIENTE = CLI.CODICE AND CLI.DOMINIO ='CLI'
	LEFT OUTER JOIN PARAMETRI AS PCO
		ON MOD.PARTE_INTERESSATA = PCO.CODICE AND PPE.DOMINIO ='PCO'
	LEFT OUTER JOIN PARAMETRI AS PPE2
		ON MOD.PRODOTTO_RILASCIATO = PPE2.CODICE AND PPE2.DOMINIO ='PPE'
	LEFT OUTER JOIN PARAMETRI AS INL2
		ON MOD.LIVELLO_INCIDENTE = INL2.CODICE AND INL2.DOMINIO ='INL'
	LEFT OUTER JOIN PARAMETRI AS PCO2
		ON MOD.PARTE_INTERESSATA = PCO2.CODICE AND PCO2.DOMINIO ='PCO'
	LEFT OUTER JOIN PARAMETRI AS OOE2
		ON MOD.CODICE_ORE_LOCALE = OOE2.CODICE AND OOE2.DOMINIO ='OOE'
	LEFT OUTER JOIN PARAMETRI AS MME2
		ON MOD.CODICE_MIN_LOCALE = MME2.CODICE AND MME2.DOMINIO ='MME'
	LEFT OUTER JOIN PARAMETRI AS GGE
		ON MOD.CODICE_GIORNI = GGE.CODICE AND GGE.DOMINIO ='GGE'
	LEFT OUTER JOIN PARAMETRI AS OOE
		ON MOD.CODICE_ORE = OOE.CODICE AND OOE.DOMINIO ='OOE'
	LEFT OUTER JOIN PARAMETRI AS MME
		ON MOD.CODICE_MIN = MME.CODICE AND MME.DOMINIO ='MME'
	LEFT OUTER JOIN PARAMETRI AS UNI1
		ON MOD.UNITA_RILASCIATA = UNI1.CODICE AND UNI1.DOMINIO ='UNI'
	LEFT OUTER JOIN PARAMETRI AS UNI2
		ON MOD.UNITA_MAX_PERMESSA = UNI2.CODICE AND UNI2.DOMINIO ='UNI'

;





-- view [V_LIMOD13]
DROP VIEW IF exists V_LIMOD13;

CREATE VIEW V_LIMOD13
AS
SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM LIMOD13 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;



-- view [V_LIMOD53]
DROP VIEW IF exists V_LIMOD53;

CREATE VIEW V_LIMOD53
AS
SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM LIMOD53 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;




-- view [V_ALIMOD52]
DROP VIEW IF exists V_LIMOD53;

CREATE VIEW V_LIMOD53
AS
SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM LIMOD53 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;





-- view [V_ALIMOD50_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD50_DETTAGLIO;

CREATE VIEW V_ALIMOD50_DETTAGLIO
AS
SELECT 
	DET.* 
	,SAZ.DESCRIZIONE AS DESCR_STATO_AZIONE
	,ACT.DESCRIZIONE AS DESCR_TIPO_AZIONE
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
FROM ALIMOD50_DETTAGLI AS DET
LEFT OUTER JOIN PARAMETRI AS SAZ
ON SAZ.CODICE=DET.STATO_AZIONE AND SAZ.DOMINIO = 'SAZ'
LEFT OUTER JOIN PARAMETRI AS ACT
ON ACT.CODICE=DET.CODICE_TIPO_AZIONE AND act.DOMINIO = 'ACT'
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 

;



DROP VIEW IF exists V_ALIMOD50_MASTER;
-- view [V_ALIMOD50_MASTER]
CREATE VIEW V_ALIMOD50_MASTER
AS
select 
	codice_bl
	id_azienda,
	nr_modulo,
	dt_modulo,
	codice_tipo_verifica,
	stato,
	titolo,
	id_utente_con,
	id_utente_app,
	id_modulo_parent,
	lista_allegati,	
    descr_stato,
    descr_bl,
    descr_tipo_verifica,
    descr_sito,
    descr_con,
	vad.* 	
from v_alimod50 as va
left outer join v_alimod50_dettaglio as vad
on va.id_modulo=vad.id_modulo order by va.id_modulo desc
;




-- view [V_ALIMOD51_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD51_DETTAGLIO;

CREATE VIEW V_ALIMOD51_DETTAGLIO
AS
SELECT 
	DET.* 
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
FROM ALIMOD51_DETTAGLI AS DET
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
;


-- view [V_LIMOD53_DETTAGLIO]
DROP VIEW IF exists V_LIMOD53_DETTAGLIO;

CREATE VIEW V_LIMOD53_DETTAGLIO
AS
SELECT 
	DET.* 
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
FROM LIMOD53_DETTAGLI AS DET
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
;




-- view [V_ALIMOD52_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD52_DETTAGLIO;

CREATE VIEW V_ALIMOD52_DETTAGLIO
AS
SELECT 
	DET.* 
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
	,STA.DESCRIZIONE AS DESCR_TIPO_DETTAGLIO
,CASE
  WHEN (MESE_RIUNIONE ='01') THEN 'Gennaio'
  WHEN (MESE_RIUNIONE ='02') THEN 'Febbraio'
  WHEN (MESE_RIUNIONE ='03') THEN 'Marzo'
  WHEN (MESE_RIUNIONE ='04') THEN 'Aprile'
  WHEN (MESE_RIUNIONE ='05') THEN 'Maggio'
  WHEN (MESE_RIUNIONE ='06') THEN 'Giugno'
  WHEN (MESE_RIUNIONE ='07') THEN 'Luglio'
  WHEN (MESE_RIUNIONE ='08') THEN 'Agosto'
  WHEN (MESE_RIUNIONE ='09') THEN 'Settembre'
  WHEN (MESE_RIUNIONE ='10') THEN 'Ottobre'
  WHEN (MESE_RIUNIONE ='11') THEN 'Novembre'
  WHEN (MESE_RIUNIONE ='12') THEN 'Dicembre'
  ELSE ''
END AS DESCR_MESE
FROM ALIMOD52_DETTAGLI AS DET
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
LEFT OUTER JOIN PARAMETRI AS STA
ON STA.CODICE = DET.TIPO_DETTAGLIO AND STA.DOMINIO ='M52'
;




-- view [V_ALIMOD80_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD80_DETTAGLIO;

CREATE VIEW V_ALIMOD80_DETTAGLIO
AS
SELECT 
	DET.* 
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
	,P1.DESCRIZIONE AS DESCR_CATEGORIA_PERSONALE
	,P2.DESCRIZIONE AS DESCR_TIPO_INFORTUNIO
	,P3.DESCRIZIONE AS DESCR_ATTREZZATURA_INTERESSATA
	,P4.DESCRIZIONE AS DESCR_COMP_ATTR_INTERESSATA
	,P5.DESCRIZIONE AS DESCR_GG_PROGNOSI
	,P6.DESCRIZIONE AS DESCR_LESIONE_MAGGIORE
	,P7.DESCRIZIONE AS DESCR_PARTE_CORPO
	,P8.DESCRIZIONE AS DESCR_ALTRE_LESIONI
	,P9.DESCRIZIONE AS DESCR_ALTRE_LESIONI_PARTE_CORPO
FROM ALIMOD80_DETTAGLI AS DET
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
LEFT OUTER JOIN  PARAMETRI AS P1
	ON DET.CODICE_CODICE_CATEGORIA_PERSONALE = P1.CODICE AND P1.DOMINIO ='CPE'
LEFT OUTER JOIN  PARAMETRI AS P2
	ON DET.CODICE_CODICE_TIPO_INFORTUNIO = P2.CODICE AND P2.DOMINIO ='TIF'
LEFT OUTER JOIN  PARAMETRI AS P3
	ON DET.CODICE_CODICE_ATTREZZATURA_INTERESSATA = P3.CODICE AND P3.DOMINIO ='ATI'
LEFT OUTER JOIN PARAMETRI AS P4
	ON DET.CODICE_COMP_ATTR_INTERESSATA = P4.CODICE AND P4.DOMINIO ='CAI'
LEFT OUTER JOIN  PARAMETRI AS P5
	ON DET.CODICE_GG_PROGNOSI = P5.CODICE AND P5.DOMINIO ='GGP'
LEFT OUTER JOIN PARAMETRI AS P6
	ON DET.CODICE_LESIONE_MAGGIORE = P6.CODICE AND P6.DOMINIO ='LES'
LEFT OUTER JOIN PARAMETRI AS P7
	ON DET.CODICE_PARTE_CORPO = P7.CODICE AND P7.DOMINIO ='PCO'
LEFT OUTER JOIN PARAMETRI AS P8
	ON DET.CODICE_ALTRE_LESIONI = P8.CODICE AND P8.DOMINIO ='LES'
LEFT OUTER JOIN PARAMETRI AS P9
	ON DET.CODICE_ALTRE_LESIONI_PARTE_CORPO = P9.CODICE AND P9.DOMINIO ='PCO'
;


DROP VIEW IF exists V_ALIMOD80_MASTER;
-- view [V_ALIMOD50_MASTER]
CREATE VIEW V_ALIMOD80_MASTER
AS
select *
from V_ALIMOD80
;



-- view [V_ALIMOD67]
DROP VIEW IF exists V_ALIMOD67 CASCADE;
CREATE VIEW V_ALIMOD67
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM ALIMOD67 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;



-- view [V_ALIMOD67_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD67_DETTAGLIO CASCADE;

CREATE VIEW V_ALIMOD67_DETTAGLIO
AS
SELECT 
		DET.* 
	,'' as NUMERO_AZIONE
	,'' as PERC_AVANZAMENTO
	,SAZ.DESCRIZIONE AS DESCR_STATO_AZIONE
	,ACT.DESCRIZIONE AS DESCR_TIPO_AZIONE
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
FROM ALIMOD67_DETTAGLI AS DET
LEFT OUTER JOIN PARAMETRI AS SAZ
ON SAZ.CODICE=DET.STATO_AZIONE AND SAZ.DOMINIO = 'SAZ'
LEFT OUTER JOIN PARAMETRI AS ACT
ON ACT.CODICE=DET.stato_azione AND act.DOMINIO = 'ACT'
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
;


DROP VIEW IF exists V_ALIMOD67_MASTER;
-- view [V_ALIMOD67_MASTER]
CREATE VIEW V_ALIMOD67_MASTER
AS
select
	*
from V_ALIMOD67 as dd
;




-- view [V_ALIMOD05]
DROP VIEW IF exists V_ALIMOD05;
CREATE VIEW V_ALIMOD05
AS
	SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		,CON.NOME_COGNOME DESCR_CON
	FROM ALIMOD05 AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;



-- view [V_ALIMOD05_DETTAGLIO]
DROP VIEW IF exists V_ALIMOD05_DETTAGLIO;

CREATE VIEW V_ALIMOD05_DETTAGLIO
AS
SELECT 
	DET.* 
	,'' as NUMERO_AZIONE
	,'' as PERC_AVANZAMENTO
	,INS.NOME || ' ' || INS.COGNOME AS NOME_COGNOME_INS
	,RES.NOME || ' ' || RES.COGNOME AS NOME_COGNOME_RES
FROM ALIMOD05_DETTAGLI AS DET
LEFT OUTER JOIN UTENTI AS INS
ON INS.ID_UTENTE=DET.ID_UTENTE_INS 
LEFT OUTER JOIN UTENTI AS RES
ON RES.ID_UTENTE=DET.ID_UTENTE_RES_1 
;



-- view [V_CHECKLIST]
DROP VIEW IF exists V_CHECKLIST;

CREATE VIEW V_CHECKLIST
AS
SELECT 
		MOD.*
		,STA.DESCRIZIONE AS DESCR_STATO
		,BL.DESCRIZIONE AS DESCR_BL 
		,AZ.RAGSOC AS DESCR_SITO
		--,CON.NOME_COGNOME DESCR_CON
		,MOD.REFERENTE AS DESCR_CON
	FROM checklist_agenzie AS MOD
	INNER JOIN PARAMETRI AS BL
	ON MOD.CODICE_BL = BL.CODICE AND BL.DOMINIO ='BSN'
	INNER JOIN AZIENDE AS AZ
	ON MOD.ID_AZIENDA = AZ.ID_AZIENDA
	INNER JOIN V_UTENTI AS CON
	ON MOD.ID_UTENTE_CON = CON.ID_UTENTE
	LEFT OUTER JOIN PARAMETRI AS STA
	ON STA.CODICE = MOD.STATO AND STA.DOMINIO ='STA'
;




-- view [V_QHSE_APPROVER]
DROP VIEW IF exists V_QHSE_APPROVER;

CREATE VIEW V_QHSE_APPROVER
AS
select 
	ri.id_modulo
	,ri.nr_modulo
	,ri.ID_UTENTE_CON
	,ri.nome_tabella as codice_tipo_richiesta
	,ut.username as username_con
	,az.id_azienda
	,az.ragsoc
	,stato
	,app.id_utente as id_utente_app 
	,app.username as username_app 
from (
	select 
		id_modulo
		,nr_modulo
		,id_azienda
		,stato
		,ID_UTENTE_CON
		,'ALIMOD20'::varchar as nome_tabella
	from ALIMOD20 where stato = 'DRA'
	union 
	select 
		id_modulo
		,nr_modulo
		,id_azienda
		,stato
		,ID_UTENTE_CON
		,'ALIMOD20'::varchar as nome_tabella		
	from ALIMOD50 where stato = 'DRA'
	) as ri
inner join aziende as az on ri.id_azienda=az.id_azienda
inner join utenti as ut on ri.ID_UTENTE_CON =ut.id_utente
inner join utenti_aziende as ua on ri.id_azienda=ua.id_azienda
inner join utenti as app on ua.id_utente=app.id_utente
inner join utenti_profili as up on ua.id_utente = up.id_utente
inner join profili as pr on up.id_profilo=pr.id_profilo and pr.codice='APP'
;



-- view [V_SITIQUSE_BL]
DROP VIEW IF exists V_SITIQUSE_BL;

CREATE VIEW V_SITIQUSE_BL
AS
select distinct 
	azi.id_azienda
	,azi.codice
	,azi.ragsoc
	,split.codice_bl::char(3) as codice_bl
	,bsn.descrizione as descr_bl
from aziende as azi,
unnest(string_to_array(azi.tipo_azienda, ';')) split(codice_bl)
inner join parametri as bsn 
on bsn.codice=split.codice_bl and dominio ='BSN'
where azi.tipo_azienda like '%HSE%'
;


-- view [V_UTENTI_AZIENDE_PROFILI]
DROP VIEW IF exists V_UTENTI_AZIENDE_PROFILI;

CREATE VIEW V_UTENTI_AZIENDE_PROFILI
AS
select 
	ute.id_utente
	,initcap(ute.nome::varchar) as nome
	,initcap(ute.cognome::varchar) as cognome
	,initcap(ute.nome::varchar)||' '||initcap(ute.cognome::varchar) as nome_cognome
	,uta.id_azienda
	,pro.codice as CODICE_PROFILO
from utenti as ute
inner join utenti_aziende as uta
on ute.id_utente=uta.id_utente
inner join utenti_profili as utp
on ute.id_utente=utp.id_utente
inner join profili as pro
on utp.id_profilo=pro.id_profilo
;



-- view [V_AGENZIE]
DROP VIEW IF exists V_AGENZIE;

CREATE VIEW V_AGENZIE
AS
select utenti.id_utente,agenti.username,ragsoc,coda_agente,piva,indirizzo||' - '||cap||' - '||citta as indirizzo
	,coda_agente||' - '||citta as sap_citta
from agenti
inner join utenti on agenti.username=utenti.username
;



/*======================== PDLWEB ===================================*/

-- view [V_IMPIANTI]
DROP VIEW IF exists V_IMPIANTI;

CREATE VIEW V_IMPIANTI
AS
SELECT 
	IMP.* 
	,AZI.RAGSOC AS DESCR_SITO
FROM IMPIANTI AS IMP
LEFT OUTER JOIN AZIENDE AS AZI
ON IMP.ID_AZIENDA=AZI.ID_AZIENDA
where IMP.FL_DISATTIVO = false 
;

-- view [V_AREA_LAVORO]
DROP VIEW IF exists V_AREA_LAVORO;

CREATE VIEW V_AREA_LAVORO
AS
SELECT 
	ARE.*
	,imp.descr_impianto
	,azi.id_azienda
	,azi.ragsoc	
FROM AREA_LAVORO AS ARE
left outer join impianti as imp
on imp.id_impianto=are.id_impianto
left outer join aziende as azi
on azi.id_azienda=imp.id_azienda
WHERE ARE.FL_DISATTIVO = false 
;


-- view [V_EQUIPMENT]
DROP VIEW IF exists V_EQUIPMENT;

CREATE VIEW V_EQUIPMENT
AS
SELECT 
	EQU.*
	,are.descr_area
	,imp.id_impianto
	,imp.descr_impianto
	,azi.id_azienda
	,azi.ragsoc
	,EQU.ID_EQUIPMENT::VARCHAR||'|'||FL_EIS::VARCHAR AS ID_EQUIPMENT_EIS
FROM EQUIPMENT AS EQU
left outer join area_lavoro as are
on equ.id_area=are.id_area
left outer join impianti as imp
on imp.id_impianto=are.id_impianto
left outer join aziende as azi
on azi.id_azienda=imp.id_azienda
WHERE EQU.FL_DISATTIVO = false 
;


-- view [V_SITIPDL]
DROP VIEW IF exists V_SITIPDL;

CREATE VIEW V_SITIPDL
AS
SELECT 
	AZI.* 
FROM AZIENDE AS AZI
WHERE AZI.TIPO_AZIENDA LIKE '%PDL%' 
;

-- view [V_PDL]
DROP VIEW IF exists V_PDL;

CREATE VIEW V_PDL
AS
SELECT 
	PDL.*
	,azi.RAGSOC
	,SPL.DESCRIZIONE AS DESCR_STATO
	,IMP.DESCR_IMPIANTO
	,ARE.DESCR_AREA
	,EQI.DESCR_EQUIPMENT
	,DESCRIZIONE_DELLA_SOSPENSIONE as MOTIVO_SOSPENSIONE
	,to_char(TS_ATTIVAZIONE,'yyyy/mm/dd') as DATA_ULTIMA_ATTIVAZIONE
	,to_char(TS_ATTIVAZIONE,'HH24:MI') as ORA_UTLIMA_ATTIVAZIONE 
	,initcap(UATT.nome::text)||' '||initcap(UATT.cognome::text) as UTENTE_ULTIMA_ATTIVAZIONE
	,MDI.valore_attributo as modulo_interferenze,CASE WHEN FLG_TA THEN 'In fermata' ELSE 'Non in fermata' END as stato_fermata
FROM PDL 
left outer join aziende as azi ON PDL.ID_AZIENDA=azi.ID_AZIENDA 
left outer join impianti as IMP ON PDL.ID_IMPIANTO=IMP.ID_IMPIANTO and  PDL.ID_AZIENDA= IMP.ID_AZIENDA
left outer join area_lavoro as ARE ON PDL.ID_AREA= ARE.ID_AREA AND PDL.ID_IMPIANTO= ARE.ID_IMPIANTO
left outer join equipment as EQI ON PDL.ID_EQUIPMENT= EQI.ID_EQUIPMENT AND PDL.ID_AREA= EQI.ID_AREA
left outer join utenti as UATT on PDL.ID_UTENTE_ATTIVAZIONE = UATT.ID_UTENTE
left outer join parametri as SPL ON PDL.STATO= SPL.CODICE and SPL.DOMINIO='SPL'
left outer join ATTRIBUTI_AZIENDA as MDI on PDL.ID_AZIENDA=MDI.ID_AZIENDA and  MDI.codice_attributo= 'MODULO_INTERFERENZE'
;




-- view [V_IMPRESE]
DROP VIEW IF exists V_IMPRESE;

CREATE VIEW V_IMPRESE
AS
SELECT 
	DISTINCT NOME_IMPRESA
FROM PREPOSTI_IMPRESA 
;

-- view [V_IMPRESE]
DROP VIEW IF exists V_IMPRESE;

CREATE VIEW V_IMPRESE
AS
SELECT 
	DISTINCT NOME_IMPRESA
	,ID_AZIENDA
FROM PREPOSTI_IMPRESA 
;


-- view [V_PREPOSTI_IMPRESA]
DROP VIEW IF exists V_PREPOSTI_IMPRESA;

CREATE VIEW V_PREPOSTI_IMPRESA
AS
SELECT 
	ID_PREPOSTO_IMPRESA
	,PI.ID_AZIENDA
	,AZ.RAGSOC
	,NOME_IMPRESA
	,NOME_COGNOME_PREPOSTO_IMPRESA
FROM PREPOSTI_IMPRESA as PI
left outer join AZIENDE as AZ
on PI.ID_AZIENDA = AZ.ID_AZIENDA
;

-- view [V_UTENTI_PROFILI_AZIENDE]
DROP VIEW IF exists V_UTENTI_PROFILI_AZIENDE;

CREATE VIEW V_UTENTI_PROFILI_AZIENDE
AS
SELECT 
	ut.id_utente
	,nome
	,cognome
	,nome||' '||cognome as NOME_COGNOME 
	,pr.codice as profilo
	,ua.id_azienda
FROM UTENTI as ut
inner join utenti_profili as up on up.id_utente= ut.id_utente 
inner join profili as pr on up.id_profilo=pr.id_profilo 
inner join utenti_aziende as ua on up.id_utente = ua.id_utente
inner join aziende as az on ua.id_azienda=az.id_azienda and tipo_azienda like '%PDL%';
;


-- view [V_STRUTTURA_TREE]
DROP VIEW IF exists V_STRUTTURA_TREE;

CREATE VIEW V_STRUTTURA_TREE
AS
select 
	1 as livello
	,'sito_'||id_azienda::varchar as id
	,'#' as parent
	,replace(ragsoc,'"','\"') as node_text
	,id_azienda
	,'fa fa-building fa-2x' as icon
	,null::integer as id_impianto
	,null::integer as id_area
	,null::integer as id_equipment
from aziende 
where tipo_azienda like '%PDL%'
union
select 
	2 as livello
	,'impianto_'||id_impianto::varchar as id
	,'sito_'||id_azienda::varchar as parent
	,replace(descr_impianto,'"','\"') as node_text
	,id_azienda
	,'fa fa-industry fa-2x' as icon
	,id_impianto
	,null::integer as id_area
	,null::integer as id_equipment
from impianti where fl_disattivo=false
union
select 
	3 as livello
	,'area_'||id_area::varchar as id
	,'impianto_'||are.id_impianto::varchar as parent
	,replace(descr_area,'"','\"') as node_text
	,imp.id_azienda
	,'fa fa-sitemap fa-2x' as icon
	,are.id_impianto
	,are.id_area
	,null::integer as id_equipment
from area_lavoro as are 
left outer join impianti as imp on are.id_impianto = imp.id_impianto 
where are.fl_disattivo=false
union
select 
	4 as livello
	,'id_'||imp.id_azienda::varchar||'_'||are.id_impianto::varchar||'_'||equ.id_area::varchar||'_'||id_equipment::varchar as id
	,'area_'||equ.id_area::varchar as parent
	,replace(descr_equipment,'"','\"') as node_text
	,imp.id_azienda	
	,'fa fa-cogs fa-2x' as icon
	,are.id_impianto
	,equ.id_area
	,equ.id_equipment
from equipment as equ
left outer join area_lavoro as are on are.id_area = equ.id_area 
left outer join impianti as imp on are.id_impianto = imp.id_impianto 
where equ.fl_disattivo=false
UNION
select 
	5 as livello
	,'iid_'||imp.id_azienda::varchar||'_'||are.id_impianto::varchar||'_'||equ.id_area::varchar||'_'||id_equipment::varchar as id
	,'id_'||imp.id_azienda::varchar||'_'||are.id_impianto::varchar||'_'||equ.id_area::varchar||'_'||id_equipment::varchar as parent
	,'Nuovo PdL' as node_text
	,imp.id_azienda	
	,'fa fa-file-o' as icon
	,are.id_impianto
	,equ.id_area
	,equ.id_equipment
from equipment as equ
left outer join area_lavoro as are on are.id_area = equ.id_area 
left outer join impianti as imp on are.id_impianto = imp.id_impianto 
where equ.fl_disattivo=false
UNION
select 
	5 as livello
	,'sid_'||imp.id_azienda::varchar||'_'||are.id_impianto::varchar||'_'||equ.id_area::varchar||'_'||id_equipment::varchar as id
	,'id_'||imp.id_azienda::varchar||'_'||are.id_impianto::varchar||'_'||equ.id_area::varchar||'_'||id_equipment::varchar as parent
	,'Ricerca PdL' as node_text
	,imp.id_azienda	
	,'fa fa-search' as icon
	,are.id_impianto
	,equ.id_area
	,equ.id_equipment
from equipment as equ
left outer join area_lavoro as are on are.id_area = equ.id_area 
left outer join impianti as imp on are.id_impianto = imp.id_impianto 
where equ.fl_disattivo=false
;




-- view V_GRAFICO1
DROP VIEW IF EXISTS V_GRAFICO1;
CREATE VIEW V_GRAFICO1 
AS
select dt_pdl,count(*) as totale from pdl where dt_pdl between 
to_char(cast(date_trunc('month', current_date) as date),'YYYY/mm/DD')
and 
to_char(cast(date_trunc('month', current_date)+'1month'::interval-'1day'::interval  as date),'YYYY/mm/DD') 
group by dt_pdl order by dt_pdl
;


