/*
CREATED: 22/10/2017
MODIFIED: 17/12/2017
MODEL: POSTGRESQL 9.4
DATABASE: POSTGRESQL 9.4
*/


-- DROP INDEXES SECTION -------------------------------------------------

DROP INDEX IF EXISTS IDX_UTENTI_UTENZE_PK
;
DROP INDEX IF EXISTS IDX_UTENTI_UTENZE_FK
;


-- DROP TABLES SECTION ---------------------------------------------------

DROP TABLE IF EXISTS UTENTI_UTENZE CASCADE
;

-- CREATE TABLES SECTION -------------------------------------------------


-- TABLE UTENTI_UTENZE

CREATE TABLE UTENTI_UTENZE(
 ID_UTENTE_UTENZA SERIAL NOT NULL,
 ID_UTENZA INTEGER NOT NULL,
 ID_UTENTE INTEGER NOT NULL
)
;

-- CREATE INDEXES FOR TABLE UTENTI_UTENZE

CREATE INDEX IDX_UTENTI_UTENZE_PK ON UTENTI_UTENZE (ID_UTENTE_UTENZA)
;

CREATE INDEX IDX_UTENTI_UTENZE_FK ON UTENTI_UTENZE (ID_UTENTE,ID_UTENZA)
;




ALTER TABLE UTENTI_UTENZE ADD CONSTRAINT RELATIONSHIP60 FOREIGN KEY (ID_UTENZA) REFERENCES UTENZE (ID_MODULO) ON DELETE CASCADE ON UPDATE NO ACTION
;
