insert into parametri (dominio,codice,descrizione) values ('ERR','700','01-Anomalia sonda 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','701','01-Error 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','702','02-Anomalia sonda 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','703','02-Error 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','704','03-Anomalia sonda 3');
insert into parametri (dominio,codice,descrizione) values ('ERR','705','03-Error 3');
insert into parametri (dominio,codice,descrizione) values ('ERR','706','04-Anomalia sonda 4');
insert into parametri (dominio,codice,descrizione) values ('ERR','707','04-Error 4');
insert into parametri (dominio,codice,descrizione) values ('ERR','708','05-Error 5');
insert into parametri (dominio,codice,descrizione) values ('ERR','709','05-Inversione sonde 1 e 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','710','06-Error 6');
insert into parametri (dominio,codice,descrizione) values ('ERR','711','06-Inversione sonde 3 e 4');
insert into parametri (dominio,codice,descrizione) values ('ERR','712','07-Error 7');
insert into parametri (dominio,codice,descrizione) values ('ERR','713','07-Guasto misuratore C1');
insert into parametri (dominio,codice,descrizione) values ('ERR','714','08-Error 8');
insert into parametri (dominio,codice,descrizione) values ('ERR','715','08-Guasto misuratore C2');
insert into parametri (dominio,codice,descrizione) values ('ERR','716','09-Anomalia misuratore C1');
insert into parametri (dominio,codice,descrizione) values ('ERR','717','09-Error 9');
insert into parametri (dominio,codice,descrizione) values ('ERR','718','10-Anomalia misuratore C2');
insert into parametri (dominio,codice,descrizione) values ('ERR','719','10-Error 10');
insert into parametri (dominio,codice,descrizione) values ('ERR','720','11-Anomalia misuratore C3');
insert into parametri (dominio,codice,descrizione) values ('ERR','721','11-Error 11');
insert into parametri (dominio,codice,descrizione) values ('ERR','722','12-Anomalia misuratore C4');
insert into parametri (dominio,codice,descrizione) values ('ERR','723','12-Error 12');
insert into parametri (dominio,codice,descrizione) values ('ERR','724','13-Anomalia scheda elettronica');
insert into parametri (dominio,codice,descrizione) values ('ERR','725','13-Error 13');
insert into parametri (dominio,codice,descrizione) values ('ERR','726','14-Anomalie varie');
insert into parametri (dominio,codice,descrizione) values ('ERR','727','14-Error 14');
insert into parametri (dominio,codice,descrizione) values ('ERR','728','15-Error 15');
insert into parametri (dominio,codice,descrizione) values ('ERR','729','15-Guasto mem EEPROM');
insert into parametri (dominio,codice,descrizione) values ('ERR','730','16-Anomalia BUS locale');
insert into parametri (dominio,codice,descrizione) values ('ERR','731','16-Error 16');
insert into parametri (dominio,codice,descrizione) values ('ERR','732','Allarme applicazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','733','Application busy');
insert into parametri (dominio,codice,descrizione) values ('ERR','734','Applicazione occupata');
insert into parametri (dominio,codice,descrizione) values ('ERR','735','Batteria Scarica');
insert into parametri (dominio,codice,descrizione) values ('ERR','736','Blocco');
insert into parametri (dominio,codice,descrizione) values ('ERR','737','Burst in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','738','Capacita di applicazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','739','Checksum');
insert into parametri (dominio,codice,descrizione) values ('ERR','740','Corrente bassa');
insert into parametri (dominio,codice,descrizione) values ('ERR','741','Differenza Temp. negativa');
insert into parametri (dominio,codice,descrizione) values ('ERR','742','Errore batteria');
insert into parametri (dominio,codice,descrizione) values ('ERR','743','Errore bobina');
insert into parametri (dominio,codice,descrizione) values ('ERR','744','Errore checksum');
insert into parametri (dominio,codice,descrizione) values ('ERR','745','Errore comunicaz. ripartitori');
insert into parametri (dominio,codice,descrizione) values ('ERR','746','Errore costante');
insert into parametri (dominio,codice,descrizione) values ('ERR','747','Errore di memorizzazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','748','Errore E2PROM');
insert into parametri (dominio,codice,descrizione) values ('ERR','749','Errore funzionamento');
insert into parametri (dominio,codice,descrizione) values ('ERR','750','Errore generico');
insert into parametri (dominio,codice,descrizione) values ('ERR','751','Errore manomissione');
insert into parametri (dominio,codice,descrizione) values ('ERR','752','Errore memoria');
insert into parametri (dominio,codice,descrizione) values ('ERR','753','Errore memorizzazione dato');
insert into parametri (dominio,codice,descrizione) values ('ERR','754','Errore misura riferimento');
insert into parametri (dominio,codice,descrizione) values ('ERR','755','Errore perdita');
insert into parametri (dominio,codice,descrizione) values ('ERR','756','Errore permanente');
insert into parametri (dominio,codice,descrizione) values ('ERR','757','Errore range misurazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','758','Errore riferimento');
insert into parametri (dominio,codice,descrizione) values ('ERR','759','Errore ripartitori');
insert into parametri (dominio,codice,descrizione) values ('ERR','760','Errore sensore');
insert into parametri (dominio,codice,descrizione) values ('ERR','761','Errore sensore temp mandata');
insert into parametri (dominio,codice,descrizione) values ('ERR','762','Errore sensore temp ritorno');
insert into parametri (dominio,codice,descrizione) values ('ERR','763','Errore sensore temperatura di ingresso');
insert into parametri (dominio,codice,descrizione) values ('ERR','764','Errore sensore temperatura di ingresso/non connesso');
insert into parametri (dominio,codice,descrizione) values ('ERR','765','Errore sensore temperatura di ritorno');
insert into parametri (dominio,codice,descrizione) values ('ERR','766','Errore sensore temperatura di ritorno/non connesso');
insert into parametri (dominio,codice,descrizione) values ('ERR','767','Errore Somma');
insert into parametri (dominio,codice,descrizione) values ('ERR','768','Errore sonda mandata');
insert into parametri (dominio,codice,descrizione) values ('ERR','769','Errore sonda ritorno');
insert into parametri (dominio,codice,descrizione) values ('ERR','770','Errore sonde');
insert into parametri (dominio,codice,descrizione) values ('ERR','771','Errore sonde permanente');
insert into parametri (dominio,codice,descrizione) values ('ERR','772','Errore temporaneo');
insert into parametri (dominio,codice,descrizione) values ('ERR','773','Flag Bit 0');
insert into parametri (dominio,codice,descrizione) values ('ERR','774','Flag Bit 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','775','Flag Bit 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','776','Flag Bit 3');
insert into parametri (dominio,codice,descrizione) values ('ERR','777','Flag Bit 4');
insert into parametri (dominio,codice,descrizione) values ('ERR','778','Flag Bit 5');
insert into parametri (dominio,codice,descrizione) values ('ERR','779','Flag Bit 6');
insert into parametri (dominio,codice,descrizione) values ('ERR','780','Flag Bit 7');
insert into parametri (dominio,codice,descrizione) values ('ERR','781','Flusso inverso');
insert into parametri (dominio,codice,descrizione) values ('ERR','782','Flusso inverso in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','783','Flusso inverso rilevato');
insert into parametri (dominio,codice,descrizione) values ('ERR','784','Frode magnetica in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','785','Frode magnetica rilevata');
insert into parametri (dominio,codice,descrizione) values ('ERR','786','Frode meccanica in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','787','Frode meccanica rilevata');
insert into parametri (dominio,codice,descrizione) values ('ERR','788','Magnete prog presente');
insert into parametri (dominio,codice,descrizione) values ('ERR','789','Manipolazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','790','Manomissione');
insert into parametri (dominio,codice,descrizione) values ('ERR','791','Manomissione in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','792','Meter oversized');
insert into parametri (dominio,codice,descrizione) values ('ERR','793','Meter undersized');
insert into parametri (dominio,codice,descrizione) values ('ERR','794','Ore max funzionamento superate');
insert into parametri (dominio,codice,descrizione) values ('ERR','795','Ostruzione');
insert into parametri (dominio,codice,descrizione) values ('ERR','796','Perdita');
insert into parametri (dominio,codice,descrizione) values ('ERR','797','Perdita in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','798','Perdita rilevata');
insert into parametri (dominio,codice,descrizione) values ('ERR','799','Portata negativa');
insert into parametri (dominio,codice,descrizione) values ('ERR','800','Potenza debole');
insert into parametri (dominio,codice,descrizione) values ('ERR','801','Potenza negativa');
insert into parametri (dominio,codice,descrizione) values ('ERR','802','Power Low');
insert into parametri (dominio,codice,descrizione) values ('ERR','803','Protezione scrittura');
insert into parametri (dominio,codice,descrizione) values ('ERR','804','Radio');
insert into parametri (dominio,codice,descrizione) values ('ERR','805','Reset');
insert into parametri (dominio,codice,descrizione) values ('ERR','806','Sensore acceso');
insert into parametri (dominio,codice,descrizione) values ('ERR','807','Tutti errori di applicazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','808','Guasto hardware');
insert into parametri (dominio,codice,descrizione) values ('ERR','809','Periodo taratura superato');
insert into parametri (dominio,codice,descrizione) values ('ERR','810','Errore modulo');
insert into parametri (dominio,codice,descrizione) values ('ERR','811','Raffrescamento disponibile');
insert into parametri (dominio,codice,descrizione) values ('ERR','812','Massima portata superata');
insert into parametri (dominio,codice,descrizione) values ('ERR','813','Anomalia sonda andata 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','814','Anomalia sonda ritorno 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','815','Anomalia valvola 1');
insert into parametri (dominio,codice,descrizione) values ('ERR','816','Anomalia sonda andata 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','817','Anomalia sonda ritorno 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','818','Anomalia valvola 2');
insert into parametri (dominio,codice,descrizione) values ('ERR','819','Anomalia batteria');
insert into parametri (dominio,codice,descrizione) values ('ERR','820','Allarme bit 7');
insert into parametri (dominio,codice,descrizione) values ('ERR','821','Allarme bit 8');
insert into parametri (dominio,codice,descrizione) values ('ERR','822','Allarme bit 9');
insert into parametri (dominio,codice,descrizione) values ('ERR','823','Allarme bit 10');
insert into parametri (dominio,codice,descrizione) values ('ERR','824','Allarme bit 11');
insert into parametri (dominio,codice,descrizione) values ('ERR','825','Allarme bit 12');
insert into parametri (dominio,codice,descrizione) values ('ERR','826','Allarme bit 13');
insert into parametri (dominio,codice,descrizione) values ('ERR','827','Allarme bit 14');
insert into parametri (dominio,codice,descrizione) values ('ERR','828','Allarme bit 15');
insert into parametri (dominio,codice,descrizione) values ('ERR','829','Errore sensore prolungato');
insert into parametri (dominio,codice,descrizione) values ('ERR','830','Errore di comunicazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','831','Reset ai parametri di default');
insert into parametri (dominio,codice,descrizione) values ('ERR','832','Errore oscillatore');
insert into parametri (dominio,codice,descrizione) values ('ERR','833','Errore di misurazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','834','Errore dati calibrazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','835','Parametrizzazione persa');
insert into parametri (dominio,codice,descrizione) values ('ERR','836','Errore memorizzazione L1');
insert into parametri (dominio,codice,descrizione) values ('ERR','837','Errore memorizzazione L2');
insert into parametri (dominio,codice,descrizione) values ('ERR','838','Temperatura fuori range');
insert into parametri (dominio,codice,descrizione) values ('ERR','839','Errore modulo radio');
insert into parametri (dominio,codice,descrizione) values ('ERR','840','Errore di misurazione rilevato');
insert into parametri (dominio,codice,descrizione) values ('ERR','841','Errore oscillatore rilevato');
insert into parametri (dominio,codice,descrizione) values ('ERR','842','Errore perdita alimentazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','843','Errore rilevazione consumo in corso');
insert into parametri (dominio,codice,descrizione) values ('ERR','844','Errore rilevazione consumo rilevato');
insert into parametri (dominio,codice,descrizione) values ('ERR','845','Sensore invertito');
insert into parametri (dominio,codice,descrizione) values ('ERR','846','Sonda 1 danneggiata');
insert into parametri (dominio,codice,descrizione) values ('ERR','847','Sonda 2 danneggiata');
insert into parametri (dominio,codice,descrizione) values ('ERR','848','Sonda 1 corto circuito');
insert into parametri (dominio,codice,descrizione) values ('ERR','849','Sonda 2 corto circuito');
insert into parametri (dominio,codice,descrizione) values ('ERR','850','Errore misurazione portata o bobina');
insert into parametri (dominio,codice,descrizione) values ('ERR','851','Errore temporaneo');
insert into parametri (dominio,codice,descrizione) values ('ERR','852','Errore permanente');
insert into parametri (dominio,codice,descrizione) values ('ERR','853','Allarme applicazione');
insert into parametri (dominio,codice,descrizione) values ('ERR','854','Allarme magnete interno');
insert into parametri (dominio,codice,descrizione) values ('ERR','855','Rilevato rottura vetri');
insert into parametri (dominio,codice,descrizione) values ('ERR','856','Allarme attivo');
insert into parametri (dominio,codice,descrizione) values ('ERR','857','Test manuale');
insert into parametri (dominio,codice,descrizione) values ('ERR','858','Malfunzionamento');
insert into parametri (dominio,codice,descrizione) values ('ERR','859','Errore hardware sensore di fumo');
insert into parametri (dominio,codice,descrizione) values ('ERR','860','Nessuna connessione al sensore di fumo');
insert into parametri (dominio,codice,descrizione) values ('ERR','861','Fine ciclo di vita');
insert into parametri (dominio,codice,descrizione) values ('ERR','862','Allarme cavo esterno');
insert into parametri (dominio,codice,descrizione) values ('ERR','863','Superamento soglia max temperatura radiatore');
insert into parametri (dominio,codice,descrizione) values ('ERR','864','Superamento soglia min temperatura radiatore');
insert into parametri (dominio,codice,descrizione) values ('ERR','865','Superamento soglia max temperatura ambiente');
insert into parametri (dominio,codice,descrizione) values ('ERR','866','Superamento soglia min temperatura ambiente');
insert into parametri (dominio,codice,descrizione) values ('ERR','867','Avaria tasto');
insert into parametri (dominio,codice,descrizione) values ('ERR','868','Test allarme');
insert into parametri (dominio,codice,descrizione) values ('ERR','869','Allarme fumo');
insert into parametri (dominio,codice,descrizione) values ('ERR','870','Rilevamento ostruzione');
insert into parametri (dominio,codice,descrizione) values ('ERR','871','Monitoraggio area circostante');
insert into parametri (dominio,codice,descrizione) values ('ERR','872','Guasto LED');
insert into parametri (dominio,codice,descrizione) values ('ERR','873','Batteria fine ciclo di vita');
insert into parametri (dominio,codice,descrizione) values ('ERR','874','Preallarme sistema rilevamento fumo sporco');
insert into parametri (dominio,codice,descrizione) values ('ERR','875','Allarme sistema rilevamento fumo sporco');
insert into parametri (dominio,codice,descrizione) values ('ERR','876','Guasto allarme acustico');
insert into parametri (dominio,codice,descrizione) values ('ERR','877','Rilevamento rimozione');