-- Drop views 

drop VIEW if exists V_UTENTI_PROFILI cascade;
DROP VIEW IF exists v_menu CASCADE;
DROP VIEW IF exists v_menu_tree;
DROP VIEW IF exists V_AZIENDE_TREE;
DROP VIEW IF exists V_DIPENDENTI;
DROP VIEW IF exists V_UTENTI;
DROP VIEW IF exists V_LOGIN;




-- view V_UTENTI_PROFILI
CREATE VIEW V_UTENTI_PROFILI 
AS
SELECT
	UPR.ID_UTENTE
	,PRF.CODICE
	,PRF.DESCRIZIONE
FROM UTENTI_PROFILI AS UPR
LEFT OUTER JOIN PROFILI AS PRF
ON UPR.ID_PROFILO = PRF.ID_PROFILO
;


-- view V_MENU
CREATE VIEW V_MENU AS 
 SELECT me.id_menu,
    me.id_menu_sup,
	me.alias,
    me.ordine,
    ml.descrizione,
    LI.codice_iso,
    me.link,
	me.icon
   FROM menu me
   INNER JOIN menu_lingue AS ML 
   ON me.id_menu = ml.id_menu
   INNER JOIN LINGUE_ISO AS LI
   ON ML.ID_LINGUE_ISO=LI.ID_LINGUE_ISO
;


-- view v_menu_tree
CREATE VIEW v_menu_tree AS 
WITH RECURSIVE v_menu_tree(
	id_menu_sup
	,descrizione_sup
	,link_sup
	,id_menu
	,alias
	,icon
	,descrizione
	,link
	,path
	,path_descri
	,link_chain
	,depth
	,codice_iso) AS (
	SELECT 
		r.id_menu_sup
		,p1.descrizione AS descrizione_sup
		,p1.link AS link_sup
		,r.id_menu
		,R.ALIAS 
		,R.ICON
		,p2.descrizione
		,p2.link
		,lpad(r.ordine::varchar, 4, '0') AS path
		,'Home / ' || r.descrizione::varchar AS path_descri
	        ,'astro?FUNCTIONID=Home;' || P2.LINK  as LINK_CHAIN		
        	,1 as DEPTH
		,r.codice_iso
	FROM v_menu as r
		,v_menu as p1
		,v_menu as p2
	WHERE r.id_menu_sup = (SELECT id_menu FROM menu WHERE id_menu_sup IS NULL) 
		AND p1.id_menu = r.id_menu_sup AND p1.codice_iso = r.codice_iso 
		AND p2.id_menu = r.id_menu AND p2.codice_iso = r.codice_iso 
		AND p1.codice_iso = p2.codice_iso
	UNION ALL
	SELECT 
		r.id_menu_sup
		,p1.descrizione AS descrizione_sup
		,p1.link AS link_sup
		,r.id_menu
		,R.ALIAS
		,R.ICON
		,p2.descrizione
		,p2.link
		,nd.path || lpad(r.ordine::varchar, 4, '0') as path
		,nd.path_descri|| ' / ' || r.descrizione AS path_descri
        	,LINK_CHAIN || ';' || P2.LINK  as LINK_CHAIN
		,nd.depth + 1
		,r.codice_iso
	FROM v_menu as r
		,v_menu as p1
		,v_menu as p2
		,v_menu_tree as nd
	WHERE 
		R.ID_MENU_SUP not in (SELECT ID_MENU FROM V_MENU WHERE ID_MENU_SUP IS  NULL) 
		and r.id_menu_sup = nd.id_menu AND r.codice_iso = nd.codice_iso 
		AND p1.id_menu = r.id_menu_sup AND p1.codice_iso = r.codice_iso 
		AND p2.id_menu = r.id_menu AND p2.codice_iso = r.codice_iso
)
SELECT DISTINCT * FROM v_menu_tree
UNION ALL
SELECT id_menu_sup
	,'' AS descrizione_sup
	,'' AS link_sup
	,id_menu
	,'Home' AS ALIAS
	,'fa fa-home' AS ICON
	,descrizione
	,link
	,'' AS path
	,'Home' AS path_descri
	,'astro?FUNCTIONID=Home' AS LINK_CHAIN
    	,0 AS depth
    	,codice_iso
FROM v_menu 
WHERE id_menu_sup IS NULL
;



-- view V_AZIENDE_TREE
CREATE VIEW V_AZIENDE_TREE AS 
WITH RECURSIVE V_AZIENDE_TREE(
		ID_AZIENDA_PARENT
		, RAGSOC_SUP
		, ID_AZIENDA
		, ALIAS_AZIENDA
		, RAGSOC
		, PATH
		, DEPTH
	) as (
	SELECT
		ID_AZIENDA_PARENT
		, ''::varchar AS RAGSOC_SUP
		, ID_AZIENDA
		, ALIAS_AZIENDA
		, RAGSOC
		, LPAD(ID_AZIENDA::varchar, 5, '0') as PATH
		, 0 AS DEPTH
		, TIPO_AZIENDA
		, CODICE
	FROM AZIENDE WHERE ID_AZIENDA_PARENT IS NULL
    UNION ALL
    SELECT
        R.ID_AZIENDA_PARENT, 
        P1.RAGSOC::varchar AS RAGSOC_SUP,
        R.ID_AZIENDA, 
		R.ALIAS_AZIENDA ,
        P2.RAGSOC,
        PATH || '>' || LPAD(R.ID_AZIENDA::varchar, 5, '0') as PATH, 
        ND.DEPTH + 1
        , R.TIPO_AZIENDA
		, R.CODICE
    FROM AZIENDE AS R
		,AZIENDE AS P1
		,AZIENDE AS P2,
        V_AZIENDE_TREE AS ND
    WHERE R.ID_AZIENDA_PARENT IS NOT NULL
	AND R.ID_AZIENDA_PARENT = ND.ID_AZIENDA 
    AND P1.ID_AZIENDA = R.ID_AZIENDA_PARENT AND P2.ID_AZIENDA = R.ID_AZIENDA 
)
SELECT DISTINCT * FROM V_AZIENDE_TREE
;



-- view [V_UTENTI]
CREATE VIEW V_UTENTI AS
SELECT 	USR.ID_UTENTE 
	,USR.USERNAME 
	,LI.CODICE_ISO 
	,USR.COGNOME AS COGNOME_UTENTE 
	,USR.NOME AS NOME_UTENTE 
	,USR.NOME || ' ' || USR.COGNOME AS NOME_COGNOME
	,USR.EMAIL 
	,USR.FL_DISATTIVO 
	,USR.TS_LOGIN
	,to_char(ts_login,'yyyy/mm/dd') as DATA_ULTIMO_ACCESSO 
	,to_char(ts_login,'HH24:MI:SS') as ORA_ULTIMO_ACCESSO 	
	,PWD.PASSWORD 
	,PWD.DT_SCADENZA 
	,(SELECT string_agg(CODICE, ',') FROM V_UTENTI_PROFILI AS EF WHERE ID_UTENTE=USR.ID_UTENTE ) AS PROFILO
	,(SELECT string_agg(DESCRIZIONE, ',') FROM V_UTENTI_PROFILI AS EF WHERE ID_UTENTE=USR.ID_UTENTE ) AS DESCRIZIONE_PROFILO
	,(SELECT string_agg(UA.ID_AZIENDA::varchar, ',') FROM UTENTI_AZIENDE AS UA WHERE UA.ID_UTENTE=USR.ID_UTENTE) AS AZIENDE_UTENTE
	
	,(SELECT string_agg(AZ.RAGSOC, ',') 
		FROM UTENTI_AZIENDE AS UA
		INNER JOIN AZIENDE AS AZ
		ON UA.ID_AZIENDA=AZ.ID_AZIENDA
		WHERE UA.ID_UTENTE=USR.ID_UTENTE 
		) AS RAGSOC_AZIENDE_UTENTE

	,(SELECT string_agg(SD.ID_DIREZIONE::varchar, ',') 
		FROM STAFF_DIREZIONI AS SD
		INNER JOIN UTENTI_AZIENDE AS UA 
		ON UA.ID_UTENTE_AZIENDA=SD.ID_UTENTE_AZIENDA 
		) AS LISTA_DIREZIONI


FROM UTENTI AS USR  
LEFT OUTER JOIN PASSWORD AS PWD  
ON USR.ID_UTENTE=PWD.ID_UTENTE AND PWD.FL_VALIDA=true 
INNER JOIN UTENTI_LINGUE AS UL 
ON USR.ID_UTENTE =UL.ID_UTENTE AND UL.FL_DEFAULT=true
INNER JOIN LINGUE_ISO AS LI 
ON UL.ID_LINGUE_ISO =LI.ID_LINGUE_ISO
;


-- view [V_LOGIN]
CREATE VIEW V_LOGIN
AS
SELECT 	USR.ID_UTENTE 
	,USR.USERNAME 
	,LI.CODICE_ISO 
	,USR.COGNOME AS COGNOME_UTENTE 
	,USR.NOME AS NOME_UTENTE 
	,PWD.PASSWORD 
	,PWD.DT_SCADENZA 

	,(SELECT string_agg(rtrim(CODICE), ',') 
		FROM V_UTENTI_PROFILI 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS PROFILO  

	,(SELECT string_agg(DESCRIZIONE, ',') 
		FROM V_UTENTI_PROFILI 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS DESCRIZIONE_PROFILO  


	,(SELECT string_agg(ID_AZIENDA::varchar, ',') 
		FROM UTENTI_AZIENDE 
		WHERE ID_UTENTE=USR.ID_UTENTE 
		)  AS AZIENDE_UTENTE  


	,( SELECT ALIAS_AZIENDA FROM V_AZIENDE_TREE WHERE ID_AZIENDA IN (
			SELECT ID_AZIENDA 
			FROM UTENTI_AZIENDE AS UA 
			LEFT OUTER JOIN UTENTI AS UT 
			ON UA.ID_UTENTE=UT.ID_UTENTE 
			WHERE LOWER(UT.USERNAME)=LOWER(USR.USERNAME)) ORDER BY PATH limit 1 ) AS ALIAS_AZIENDA_UTENTE 
			
	,( SELECT AZ.CODICE 
			FROM V_AZIENDE_TREE AS AT 
			LEFT OUTER JOIN AZIENDE AS AZ 
			ON AZ.ID_AZIENDA = AT.ID_AZIENDA 
			WHERE AT.ID_AZIENDA IN (
			SELECT ID_AZIENDA 
			FROM UTENTI_AZIENDE AS UA 
			LEFT OUTER JOIN UTENTI AS UT 
			ON UA.ID_UTENTE=UT.ID_UTENTE 
			WHERE LOWER(UT.USERNAME)=LOWER(USR.USERNAME)) ORDER BY PATH limit 1 ) AS CODICE_AZIENDA_UTENTE 

	,(SELECT string_agg(SD.ID_DIREZIONE::varchar, ',') 
		FROM STAFF_DIREZIONI AS SD
		INNER JOIN UTENTI_AZIENDE AS UA 
		ON UA.ID_UTENTE_AZIENDA=SD.ID_UTENTE_AZIENDA 
		) AS DIREZIONI_UTENTE
		
FROM UTENTI AS USR  
LEFT OUTER JOIN PASSWORD AS PWD  
ON USR.ID_UTENTE=PWD.ID_UTENTE AND PWD.FL_VALIDA=true 
INNER JOIN UTENTI_LINGUE AS UL 
ON USR.ID_UTENTE =UL.ID_UTENTE AND UL.FL_DEFAULT=true
INNER JOIN LINGUE_ISO AS LI 
ON LI.ID_LINGUE_ISO =UL.ID_LINGUE_ISO  
;



-- view [V_PARAMETRI]
DROP VIEW IF exists V_PARAMETRI CASCADE;

CREATE VIEW V_PARAMETRI
AS
	select  
		PAR.*
		,DOM.DESCRIZIONE AS DESCR_DOMINIO
	FROM PARAMETRI AS PAR 
	INNER JOIN PARAMETRI AS DOM
	ON PAR.DOMINIO=DOM.CODICE AND DOM.DOMINIO ='DOM'
;


-- view [V_FAMIGLIA_PRODOTTI_GAS]
DROP VIEW IF exists V_FAMIGLIA_PRODOTTI_GAS;

CREATE VIEW V_FAMIGLIA_PRODOTTI_GAS
AS
	select
		''::char(1) as EMPTY_FIELD
		,PG.*
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PG.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PG.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from FAMIGLIA_PRODOTTI_GAS AS PG
	left outer join UTENTI AS UT
	ON PG.ID_UTENTE_INS = UT.ID_UTENTE
;



-- view [V_PRODOTTI_GAS_COMP]
DROP VIEW IF exists V_PRODOTTI_GAS_COMP;

CREATE VIEW V_PRODOTTI_GAS_COMP
AS
	select
		PGC.*
		,GAS.DESCRIZIONE AS DESCR_COMPONENTE
		,STR.DESCRIZIONE AS DESCR_STRUMENTO_ANALISI
		,FQA.DESCRIZIONE AS DESCR_FREQUENZA_ANALISI
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PGC.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PGC.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from PRODOTTI_GAS_COMP AS PGC
	left outer join V_PARAMETRI AS GAS
	ON PGC.CODICE_COMPONENTE = GAS.CODICE AND GAS.DOMINIO='GAS'
	left outer join V_PARAMETRI AS STR
	ON PGC.CODICE_STRUMENTO_ANALISI = STR.CODICE AND STR.DOMINIO='STR'
	left outer join V_PARAMETRI AS FQA
	ON PGC.CODICE_FREQUENZA_ANALISI = FQA.CODICE AND FQA.DOMINIO='FQA'
	left outer join UTENTI AS UT
	ON PGC.ID_UTENTE_INS = UT.ID_UTENTE
;


-- view [V_IMPUREZZE_GARANTITE]
DROP VIEW IF exists V_IMPUREZZE_GARANTITE;

CREATE VIEW V_IMPUREZZE_GARANTITE
AS
	select
		IMG.*
		,IMP.DESCRIZIONE AS DESCR_IMPUREZZA
		,STR.DESCRIZIONE AS DESCR_STRUMENTO_ANALISI
		,FQA.DESCRIZIONE AS DESCR_FREQUENZA_ANALISI
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(IMG.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(IMG.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from IMPUREZZE_GARANTITE AS IMG
	left outer join V_PARAMETRI AS IMP
	ON IMG.CODICE_IMPUREZZA = IMP.CODICE AND IMP.DOMINIO='IMP'
	left outer join V_PARAMETRI AS STR
	ON IMG.CODICE_STRUMENTO_ANALISI = STR.CODICE AND STR.DOMINIO='STR'
	left outer join V_PARAMETRI AS FQA
	ON IMG.CODICE_FREQUENZA_ANALISI = FQA.CODICE AND FQA.DOMINIO='FQA'
	left outer join UTENTI AS UT
	ON IMG.ID_UTENTE_INS = UT.ID_UTENTE
;


-- view [V_PRODOTTI_GAS]
DROP VIEW IF exists V_PRODOTTI_GAS;

CREATE VIEW V_PRODOTTI_GAS
AS
	select
		PGS.*
		,FAM.DESCRIZIONE AS DESCR_FAMIGLIA_ALLESTIMENTO
		,ALS.DESCRIZIONE AS DESCR_ALLESTIMENTO
		,ADR.DESCRIZIONE AS DESCR_ETICHETTA_ADR
		,UT.NOME || ' ' ||UT.COGNOME AS UTENTE_INS
		,to_char(PGS.TS_INS,'yyyy/mm/dd') as DT_INS 
		,to_char(PGS.TS_INS,'HH24:MI:SS') as ORA_INS 	
	from PRODOTTI_GAS AS PGS
	left outer join V_PARAMETRI AS FAM
	ON PGS.CODICE_FAMIGLIA_ALLESTIMENTO = FAM.CODICE AND FAM.DOMINIO='FAM'
	left outer join V_PARAMETRI AS ALS
	ON PGS.CODICE_ALLESTIMENTO = ALS.CODICE AND ALS.DOMINIO='ALS'
	left outer join V_PARAMETRI AS ADR
	ON PGS.CODICE_ETICHETTA_ADR = ADR.CODICE AND ADR.DOMINIO='ADR'
	left outer join UTENTI AS UT
	ON PGS.ID_UTENTE_INS = UT.ID_UTENTE
;



-- view [V_DETTAGLIO_PRODOTTI]
DROP VIEW IF exists V_DETTAGLIO_PRODOTTI;

CREATE VIEW V_DETTAGLIO_PRODOTTI
AS

select 
	pg.id_prodotti_gas
	,fpg.id_famiglia
	,fpg.codice_famiglia
	,fpg.nome_commerciale
	,(SELECT string_agg(descr_componente, ',') FROM v_prodotti_gas_comp as pgc where pgc.id_famiglia=pg.id_famiglia) as composizione
	,pg.descr_famiglia_allestimento
	,pg.codice_prodotto
	,pg.descrizione_prodotto 
	,pg.codice_sap_etichetta
	,pg.codice_allestimento
	,pg.descr_allestimento
from v_prodotti_gas as pg	
inner join famiglia_prodotti_gas as fpg
on pg.id_famiglia=fpg.id_famiglia
;




-- view [V_SPECIFICHE_ALLESTIMENTI]
DROP VIEW IF exists V_SPECIFICHE_ALLESTIMENTI;

CREATE VIEW V_SPECIFICHE_ALLESTIMENTI
AS

select 
 SA.ID_SPECIFICA
 ,SA.ID_FAMIGLIA 
 ,AL.ID_ALLESTIMENTO
 ,AL.ORDINE
 ,ALS.CODICE AS CODICE_ALLESTIMENTO
 ,ALS.DESCRIZIONE AS TIPOLOGIA_ALLESTIMENTO
 ,AL.CARATTERISTICA AS CARATTERISTICA
 ,COALESCE(SA.DESCRIZIONE,'-') as DESCRIZIONE
 ,AL.FL_MATERIALE
 ,SA.ID_MATERIALE
 ,MAT.DESCRIZIONE AS DESCRIZIONE_MATERIALE
 ,MAT.CODICE_SAP
from ALLESTIMENTI as AL
LEFT OUTER join SPECIFICHE_ALLESTIMENTO as SA
ON AL.ID_ALLESTIMENTO = SA.ID_ALLESTIMENTO
LEFT OUTER JOIN FAMIGLIA_PRODOTTI_GAS AS FPG
ON FPG.ID_FAMIGLIA=SA.ID_FAMIGLIA 
LEFT OUTER JOIN PARAMETRI AS ALS 
ON ALS.CODICE = AL.CODICE_ALLESTIMENTO AND ALS.DOMINIO='ALS'
LEFT OUTER JOIN MATERIALI AS MAT 
ON SA.ID_MATERIALE = MAT.ID_MATERIALE 
;



-- view [V_ALLESTIMENTI]
DROP VIEW IF exists V_ALLESTIMENTI;

CREATE VIEW V_ALLESTIMENTI
AS

select 
 AL.*
 ,ALS.DESCRIZIONE AS DESCR_ALLESTIMENTO
from ALLESTIMENTI as AL
INNER JOIN PARAMETRI AS ALS 
ON ALS.CODICE = AL.CODICE_ALLESTIMENTO AND ALS.DOMINIO='ALS'
;


-- view [V_MATERIALI]
DROP VIEW IF exists V_MATERIALI;

CREATE VIEW V_MATERIALI
AS

select 
	*
	,DESCRIZIONE || ' - ' || CODICE_SAP AS DESCRIZIONE_E_CODICE_SAP
from MATERIALI
;

